trackList = 
[

{name:"[avex官方] A-Lin 現在我很幸福 (MV完整版).mp3",artist:"NA",src:"KKBOX_History/[avex官方] A-Lin 現在我很幸福 (MV完整版).mp3"},
{name:"[avex官方] A-Lin 給我一個理由忘記 (MV完整版).mp3",artist:"NA",src:"KKBOX_History/[avex官方] A-Lin 給我一個理由忘記 (MV完整版).mp3"},
{name:"[avex官方]羅志祥 好朋友 (MV完整版).mp3",artist:"NA",src:"KKBOX_History/[avex官方]羅志祥 好朋友 (MV完整版).mp3"},
{name:"[avex官方]羅志祥 精舞門 (MV完整版).mp3",artist:"NA",src:"KKBOX_History/[avex官方]羅志祥 精舞門 (MV完整版).mp3"},
{name:"[avex官方HD] A-Lin 幸福了 然後呢 (MV完整版).mp3",artist:"NA",src:"KKBOX_History/[avex官方HD] A-Lin 幸福了 然後呢 (MV完整版).mp3"},
{name:"《等一個人咖啡》電影主題曲＿哈林庾澄慶【缺口】官方MV.mp3",artist:"NA",src:"KKBOX_History/《等一個人咖啡》電影主題曲＿哈林庾澄慶【缺口】官方MV.mp3"},
{name:"《擺渡人》 主題曲 MV 《讓我留在你身邊》  主唱 - 陳奕迅 Eason Chan (In Cinemas 23 December).mp3",artist:"NA",src:"KKBOX_History/《擺渡人》 主題曲 MV 《讓我留在你身邊》  主唱 - 陳奕迅 Eason Chan (In Cinemas 23 December).mp3"},
{name:" 瘐澄慶《静静的》.mp3",artist:"NA",src:"KKBOX_History/瘐澄慶《静静的》.mp3"},
{name:"【我的少女時代 Our Times】Movie Theme Song - 田馥甄 Hebe Tien《小幸運 A Little Happiness》Official MV.mp3",artist:"NA",src:"KKBOX_History/【我的少女時代 Our Times】Movie Theme Song - 田馥甄 Hebe Tien《小幸運 A Little Happiness》Official MV.mp3"},
{name:"【那些年，我們一起追的女孩】電影主題曲《那些年》官方正式MV.mp3",artist:"NA",src:"KKBOX_History/【那些年，我們一起追的女孩】電影主題曲《那些年》官方正式MV.mp3"},
{name:"a MEI【三月MARCH】Official MV.mp3",artist:"NA",src:"KKBOX_History/a MEI【三月MARCH】Official MV.mp3"},
{name:"A-Lin《有一種悲傷 A Kind of Sorrow》Official Music Video - 電影『比悲傷更悲傷的故事 More Than Blue 』主題曲.mp3",artist:"NA",src:"KKBOX_History/A-Lin《有一種悲傷 A Kind of Sorrow》Official Music Video - 電影『比悲傷更悲傷的故事 More Than Blue 』主題曲.mp3"},
{name:"aMEI張惠妹 [ Full Name 連名帶姓 ] Official Music Video.mp3",artist:"NA",src:"KKBOX_History/aMEI張惠妹 [ Full Name 連名帶姓 ] Official Music Video.mp3"},
{name:"aMEI張惠妹 [ STORY THIEF 偷故事的人 ] Official Music Video.mp3",artist:"NA",src:"KKBOX_History/aMEI張惠妹 [ STORY THIEF 偷故事的人 ] Official Music Video.mp3"},
{name:"Angela Zhang & Sodagreen -  藍眼睛 - Blue Eyes.mp3",artist:"NA",src:"KKBOX_History/Angela Zhang & Sodagreen -  藍眼睛 - Blue Eyes.mp3"},
{name:"By2【我知道】官方完整版 MV（專輯：Twins）.mp3",artist:"NA",src:"KKBOX_History/By2【我知道】官方完整版 MV（專輯：Twins）.mp3"},
{name:"Della丁噹 [ 一半 ] MV官方完整高清版.mp3",artist:"NA",src:"KKBOX_History/Della丁噹 [ 一半 ] MV官方完整高清版.mp3"},
{name:"Della丁噹 [ 只是不夠愛自己Love Myself More ] Official Music Video - 中天中視「雲中歌」片尾曲.mp3",artist:"NA",src:"KKBOX_History/Della丁噹 [ 只是不夠愛自己Love Myself More ] Official Music Video - 中天中視「雲中歌」片尾曲.mp3"},
{name:"Della丁噹 [ 我沒那麼愛你Not So In Love ] MV官方完整版.mp3",artist:"NA",src:"KKBOX_History/Della丁噹 [ 我沒那麼愛你Not So In Love ] MV官方完整版.mp3"},
{name:"Della丁噹 [ 洋蔥 ] MV官方高清完整版.mp3",artist:"NA",src:"KKBOX_History/Della丁噹 [ 洋蔥 ] MV官方高清完整版.mp3"},
{name:"Della丁噹【不是你的錯Not Your Fault】MV官方完整版-三立[真愛找麻煩]插曲.mp3",artist:"NA",src:"KKBOX_History/Della丁噹【不是你的錯Not Your Fault】MV官方完整版-三立[真愛找麻煩]插曲.mp3"},
{name:"Della丁噹【手掌心】MV官方版-中視古裝大戲[蘭陵王]片尾曲.mp3",artist:"NA",src:"KKBOX_History/Della丁噹【手掌心】MV官方版-中視古裝大戲[蘭陵王]片尾曲.mp3"},
{name:"Eric周興哲《以後別做朋友 The Distance of Love》Official Music Video.mp3",artist:"NA",src:"KKBOX_History/Eric周興哲《以後別做朋友 The Distance of Love》Official Music Video.mp3"},
{name:"Eric周興哲《你，好不好？ How Have You Been》Official Music Video《遺憾拼圖》片尾曲.mp3",artist:"NA",src:"KKBOX_History/Eric周興哲《你，好不好？ How Have You Been》Official Music Video《遺憾拼圖》片尾曲.mp3"},
{name:"Eric周興哲《怎麼了 What's Wrong》Official Music Video - 華劇【你有念大學嗎？】片尾曲.mp3",artist:"NA",src:"KKBOX_History/Eric周興哲《怎麼了 What's Wrong》Official Music Video - 華劇【你有念大學嗎？】片尾曲.mp3"},
{name:"F.I.R. 飛兒樂團 - 天天夜夜 (official 官方完整版MV).mp3",artist:"NA",src:"KKBOX_History/F.I.R. 飛兒樂團 - 天天夜夜 (official 官方完整版MV).mp3"},
{name:"F.I.R. 飛兒樂團 - 月牙灣 Crescent Bay (official 官方完整版MV).mp3",artist:"NA",src:"KKBOX_History/F.I.R. 飛兒樂團 - 月牙灣 Crescent Bay (official 官方完整版MV).mp3"},
{name:"G.E.M.【多遠都要在一起 LONG DISTANCE】Official MV [HD] 鄧紫棋.mp3",artist:"NA",src:"KKBOX_History/G.E.M.【多遠都要在一起 LONG DISTANCE】Official MV [HD] 鄧紫棋.mp3"},
{name:"G.E.M.【倒數 TIK TOK】Official MV [HD] 鄧紫棋.mp3",artist:"NA",src:"KKBOX_History/G.E.M.【倒數 TIK TOK】Official MV [HD] 鄧紫棋.mp3"},
{name:"G.E.M.鄧紫棋【句號 Full Stop】Official Music Video.mp3",artist:"NA",src:"KKBOX_History/G.E.M.鄧紫棋【句號 Full Stop】Official Music Video.mp3"},
{name:"G.E.M.鄧紫棋【差不多姑娘 MISS SIMILAR 】Real Talk版 Official Music Video.mp3",artist:"NA",src:"KKBOX_History/G.E.M.鄧紫棋【差不多姑娘 MISS SIMILAR 】Real Talk版 Official Music Video.mp3"},
{name:"G.E.M.鄧紫棋【透明 Selfless】Official Music Video.mp3",artist:"NA",src:"KKBOX_History/G.E.M.鄧紫棋【透明 Selfless】Official Music Video.mp3"},
{name:"HEBE TIEN 田馥甄 [你就不要想起我 You Better Not Think About Me] Official MV HD.mp3",artist:"NA",src:"KKBOX_History/HEBE TIEN 田馥甄 [你就不要想起我 You Better Not Think About Me] Official MV HD.mp3"},
{name:"Jay Chou 周杰倫【千里之外 Far Away】-Official Music Video(ft.費玉清).mp3",artist:"NA",src:"KKBOX_History/Jay Chou 周杰倫【千里之外 Far Away】-Official Music Video(ft.費玉清).mp3"},
{name:"Jay Chou 周杰倫【不能說的祕密 Secret】-Official Music Video.mp3",artist:"NA",src:"KKBOX_History/Jay Chou 周杰倫【不能說的祕密 Secret】-Official Music Video.mp3"},
{name:"Jay Chou 周杰倫【彩虹 Rainbow】-Official Music Video.mp3",artist:"NA",src:"KKBOX_History/Jay Chou 周杰倫【彩虹 Rainbow】-Official Music Video.mp3"},
{name:"Jay Chou 周杰倫【說好的幸福呢 The Promised Love】-Official Music Video.mp3",artist:"NA",src:"KKBOX_History/Jay Chou 周杰倫【說好的幸福呢 The Promised Love】-Official Music Video.mp3"},
{name:"Jay Chou 周杰倫【稻香 Rice Field】-Official Music Video.mp3",artist:"NA",src:"KKBOX_History/Jay Chou 周杰倫【稻香 Rice Field】-Official Music Video.mp3"},
{name:"JiaJia家家 [ 家家酒Playhouse ] Official Music Video - 三立華劇「極品絕配」片尾曲.mp3",artist:"NA",src:"KKBOX_History/JiaJia家家 [ 家家酒Playhouse ] Official Music Video - 三立華劇「極品絕配」片尾曲.mp3"},
{name:"Kimberley陳芳語《愛你AINI》Official MV(HD).mp3",artist:"NA",src:"KKBOX_History/Kimberley陳芳語《愛你AINI》Official MV(HD).mp3"},
{name:"list.txt",artist:"NA",src:"KKBOX_History/list.txt"},
{name:"MAYDAY五月天 [ 因為你 所以我 Because of You ] Official Music Video.mp3",artist:"NA",src:"KKBOX_History/MAYDAY五月天 [ 因為你 所以我 Because of You ] Official Music Video.mp3"},
{name:"Mayday五月天 [ 我不願讓你一個人I Won't Let You Be Lonely ] Official Music Video - 末日版.mp3",artist:"NA",src:"KKBOX_History/Mayday五月天 [ 我不願讓你一個人I Won't Let You Be Lonely ] Official Music Video - 末日版.mp3"},
{name:"Mayday五月天 [ 後來的我們 Here, After, Us ] Official Music Video.mp3",artist:"NA",src:"KKBOX_History/Mayday五月天 [ 後來的我們 Here, After, Us ] Official Music Video.mp3"},
{name:"MAYDAY五月天 [ 派對動物Party Animal ] Official Music Video.mp3",artist:"NA",src:"KKBOX_History/MAYDAY五月天 [ 派對動物Party Animal ] Official Music Video.mp3"},
{name:"Mayday五月天[步步Step by Step]MV官方高音質HD版-電視劇「步步驚情」主題曲.mp3",artist:"NA",src:"KKBOX_History/Mayday五月天[步步Step by Step]MV官方高音質HD版-電視劇「步步驚情」主題曲.mp3"},
{name:"Mayday五月天[傷心的人別聽慢歌(貫徹快樂)]MV官方完整版-諾亞方舟3D電影主題曲.mp3",artist:"NA",src:"KKBOX_History/Mayday五月天[傷心的人別聽慢歌(貫徹快樂)]MV官方完整版-諾亞方舟3D電影主題曲.mp3"},
{name:"Mayday五月天【星空】MV官方完整版-電影「星空」主題曲.mp3",artist:"NA",src:"KKBOX_History/Mayday五月天【星空】MV官方完整版-電影「星空」主題曲.mp3"},
{name:"MP魔幻力量 [ 我還是愛著你 I still love you ] Official Music Video - 三立華劇「幸福兌換券」片尾曲.mp3",artist:"NA",src:"KKBOX_History/MP魔幻力量 [ 我還是愛著你 I still love you ] Official Music Video - 三立華劇「幸福兌換券」片尾曲.mp3"},
{name:"Rene劉若英 [ 各自安好 Each Well ] Official Music Video.mp3",artist:"NA",src:"KKBOX_History/Rene劉若英 [ 各自安好 Each Well ] Official Music Video.mp3"},
{name:"Rene劉若英[幸福不是情歌]MV官方完整版-三立華劇[兩個爸爸]片尾曲.mp3",artist:"NA",src:"KKBOX_History/Rene劉若英[幸福不是情歌]MV官方完整版-三立華劇[兩個爸爸]片尾曲.mp3"},
{name:"Ruby Siu The Taste Of Love 蕭蕭 握不住的他.mp3",artist:"NA",src:"KKBOX_History/Ruby Siu The Taste Of Love 蕭蕭 握不住的他.mp3"},
{name:"S.H.E [ 十七 ] Official Music Video.mp3",artist:"NA",src:"KKBOX_History/S.H.E [ 十七 ] Official Music Video.mp3"},
{name:"S.H.E [ 五月天 Mayday ] Official Music Video.mp3",artist:"NA",src:"KKBOX_History/S.H.E [ 五月天 Mayday ] Official Music Video.mp3"},
{name:"S.H.E [ 觸電 ] Official Music Video.mp3",artist:"NA",src:"KKBOX_History/S.H.E [ 觸電 ] Official Music Video.mp3"},
{name:"S.H.E [天灰 Grey Sky] Official Music Video.mp3",artist:"NA",src:"KKBOX_History/S.H.E [天灰 Grey Sky] Official Music Video.mp3"},
{name:"Show Lo - 獨一無二 (Only You).mp3",artist:"NA",src:"KKBOX_History/Show Lo - 獨一無二 (Only You).mp3"},
{name:"TANK [ 你的情歌 Your Love Song ] Official Music Video (電影【你的情歌】主題曲).mp3",artist:"NA",src:"KKBOX_History/TANK [ 你的情歌 Your Love Song ] Official Music Video (電影【你的情歌】主題曲).mp3"},
{name:"TANK [如果我變成回憶 If I was the memory] Official MV.mp3",artist:"NA",src:"KKBOX_History/TANK [如果我變成回憶 If I was the memory] Official MV.mp3"},
{name:"TANK [專屬天使 Personal Angel] Official Music Video (偶像劇「花樣少男少女」片尾曲).mp3",artist:"NA",src:"KKBOX_History/TANK [專屬天使 Personal Angel] Official Music Video (偶像劇「花樣少男少女」片尾曲).mp3"},
{name:"TANK [給我你的愛 Give me your love] Official Music Video.mp3",artist:"NA",src:"KKBOX_History/TANK [給我你的愛 Give me your love] Official Music Video.mp3"},
{name:"Yen-j嚴爵【好的事情 Good Things 】MV官方完整版-三立戲劇[醉後決定愛上你]片尾曲.mp3",artist:"NA",src:"KKBOX_History/Yen-j嚴爵【好的事情 Good Things 】MV官方完整版-三立戲劇[醉後決定愛上你]片尾曲.mp3"},
{name:"Yen-j嚴爵【好的情人】MV官方完整版.mp3",artist:"NA",src:"KKBOX_History/Yen-j嚴爵【好的情人】MV官方完整版.mp3"},
{name:"Yen-j嚴爵【暫時的男朋友Temporary BF】MV官方完整版.mp3",artist:"NA",src:"KKBOX_History/Yen-j嚴爵【暫時的男朋友Temporary BF】MV官方完整版.mp3"},
{name:"八三夭 831【想見你想見你想見你 Miss You 3000】電視劇「想見你???」片尾曲 Official Music Video.mp3",artist:"NA",src:"KKBOX_History/八三夭 831【想見你想見你想見你 Miss You 3000】電視劇「想見你???」片尾曲 Official Music Video.mp3"},
{name:"女也herstory with Mayday - G.E.M. 鄧紫棋 [ 你不是真正的快樂 ] Official Music Video.mp3",artist:"NA",src:"KKBOX_History/女也herstory with Mayday - G.E.M. 鄧紫棋 [ 你不是真正的快樂 ] Official Music Video.mp3"},
{name:"女也herstory with Mayday - 徐佳瑩 [ 突然好想你 ] Official Music Video.mp3",artist:"NA",src:"KKBOX_History/女也herstory with Mayday - 徐佳瑩 [ 突然好想你 ] Official Music Video.mp3"},
{name:"方大同-紅豆MV.mp3",artist:"NA",src:"KKBOX_History/方大同-紅豆MV.mp3"},
{name:"方文山電影同名主題曲【聽見下雨的聲音】完整MV 演唱魏如昀  詞方文山  曲周杰倫.mp3",artist:"NA",src:"KKBOX_History/方文山電影同名主題曲【聽見下雨的聲音】完整MV 演唱魏如昀  詞方文山  曲周杰倫.mp3"},
{name:"王力宏 Kiss Goodbye (Official Video Karaoke).mp3",artist:"NA",src:"KKBOX_History/王力宏 Kiss Goodbye (Official Video Karaoke).mp3"},
{name:"王力宏 Leehom Wang - 心跳.mp3",artist:"NA",src:"KKBOX_History/王力宏 Leehom Wang - 心跳.mp3"},
{name:"王心凌 Cyndi Wang – 從未到過的地方 (Official Music Video).mp3",artist:"NA",src:"KKBOX_History/王心凌 Cyndi Wang – 從未到過的地方 (Official Music Video).mp3"},
{name:"王心凌 Cyndi Wang  睫毛彎彎 (2005)HD.mp3",artist:"NA",src:"KKBOX_History/王心凌 Cyndi Wang  睫毛彎彎 (2005)HD.mp3"},
{name:"田馥甄 Hebe Tien [寂寞寂寞就好 Leave Me Alone] Official MV.mp3",artist:"NA",src:"KKBOX_History/田馥甄 Hebe Tien [寂寞寂寞就好 Leave Me Alone] Official MV.mp3"},
{name:"白月光与朱砂痣.mp3",artist:"NA",src:"KKBOX_History/白月光与朱砂痣.mp3"},
{name:"任然 - 飛鳥和蟬【動態歌詞】「你驕傲的飛遠 我棲息的夏天」?.mp3",artist:"NA",src:"KKBOX_History/任然 - 飛鳥和蟬【動態歌詞】「你驕傲的飛遠 我棲息的夏天」?.mp3"},
{name:"光良-約定.mp3",artist:"NA",src:"KKBOX_History/光良-約定.mp3"},
{name:"艾熱   李佳隆《星球墜落》高音質   動態歌詞版MV.mp3",artist:"NA",src:"KKBOX_History/艾熱   李佳隆《星球墜落》高音質   動態歌詞版MV.mp3"},
{name:"吳克群《沒關係》Official 完整版 MV [HD].mp3",artist:"NA",src:"KKBOX_History/吳克?《沒關係》Official 完整版 MV [HD].mp3"},
{name:"吳克群 - 為你寫詩 KTV.mp3",artist:"NA",src:"KKBOX_History/吳克群 - 為你寫詩 KTV.mp3"},
{name:"妥協 蔡依林 完整 MV Jolin Tsai (Compromise).mp3",artist:"NA",src:"KKBOX_History/妥協 蔡依林 完整 MV Jolin Tsai (Compromise).mp3"},
{name:"李玉? - ?好遇?你.mp3",artist:"NA",src:"KKBOX_History/李玉? - ?好遇?你.mp3"},
{name:"李玖哲Nicky Lee-想太多Think Too Much-完整版MV.wmv.mp3",artist:"NA",src:"KKBOX_History/李玖哲Nicky Lee-想太多Think Too Much-完整版MV.wmv.mp3"},
{name:"李佳薇 Jess Lee 『像天堂的懸崖』Cliff to the Heaven 窒愛版MV (華納official 高畫質HD官方完整版MV).mp3",artist:"NA",src:"KKBOX_History/李佳薇 Jess Lee 『像天堂的懸崖』Cliff to the Heaven 窒愛版MV (華納official 高畫質HD官方完整版MV).mp3"},
{name:"李毓芬Tia Lee《是我不夠好Not Good Enough》Official Music Video HD.mp3",artist:"NA",src:"KKBOX_History/李毓芬Tia Lee《是我不夠好Not Good Enough》Official Music Video HD.mp3"},
{name:"李聖傑 Sam Lee【眼底星空】Official Music Video.mp3",artist:"NA",src:"KKBOX_History/李聖傑 Sam Lee【眼底星空】Official Music Video.mp3"},
{name:"李聖傑-擦肩而過.mp3",artist:"NA",src:"KKBOX_History/李聖傑-擦肩而過.mp3"},
{name:"李榮浩 - 模特 Music Video.mp3",artist:"NA",src:"KKBOX_History/李榮浩 - 模特 Music Video.mp3"},
{name:"李榮浩 Ronghao Li - 不將就 Stubborn Love (Official 高畫質 HD 官方完整版 MV).mp3",artist:"NA",src:"KKBOX_History/李榮浩 Ronghao Li - 不將就 Stubborn Love (Official 高畫質 HD 官方完整版 MV).mp3"},
{name:"李榮浩 Ronghao Li - 年少有為 If I Were Young (華納 Official HD 官方MV).mp3",artist:"NA",src:"KKBOX_History/李榮浩 Ronghao Li - 年少有為 If I Were Young (華納 Official HD 官方MV).mp3"},
{name:"李榮浩 Ronghao Li - 耳朵 Ear (Official Music Video).mp3",artist:"NA",src:"KKBOX_History/李榮浩 Ronghao Li - 耳朵 Ear (Official Music Video).mp3"},
{name:"玖壹壹(Nine one one) - 來個蹦蹦? ?Ft?. ?Ella? ?陳嘉樺 Like Boom Boom Ft. Ella 官方MV首播.mp3",artist:"NA",src:"KKBOX_History/玖壹壹(Nine one one) - 來個蹦蹦? ?Ft?. ?Ella? ?陳嘉樺 Like Boom Boom Ft. Ella 官方MV首播.mp3"},
{name:"卓文萱 Genie Chuo&曹格 Gary Chaw【梁山伯與茱麗葉】華視偶像劇「戀愛女王」片尾曲 Official Music Video.mp3",artist:"NA",src:"KKBOX_History/卓文萱 Genie Chuo&曹格 Gary Chaw【梁山伯與茱麗葉】華視偶像劇「戀愛女王」片尾曲 Official Music Video.mp3"},
{name:"周杰倫 Jay Chou (特別演出 派偉俊)【告白氣球 Love Confession】Official MV.mp3",artist:"NA",src:"KKBOX_History/周杰倫 Jay Chou (特別演出 派偉俊)【告白氣球 Love Confession】Official MV.mp3"},
{name:"周杰倫 Jay Chou【Mine Mine】Official MV.mp3",artist:"NA",src:"KKBOX_History/周杰倫 Jay Chou【Mine Mine】Official MV.mp3"},
{name:"周杰倫 Jay Chou【不愛我就拉倒 If You Don't Love Me, It's Fine】Official MV 發燒影片華語地區蟬聯第一 美國直衝前二.mp3",artist:"NA",src:"KKBOX_History/周杰倫 Jay Chou【不愛我就拉倒 If You Don't Love Me, It's Fine】Official MV 發燒影片華語地區蟬聯第一 美國直衝前二.mp3"},
{name:"周杰倫 Jay Chou【夜曲 Nocturne】Official Music Video.mp3",artist:"NA",src:"KKBOX_History/周杰倫 Jay Chou【夜曲 Nocturne】Official Music Video.mp3"},
{name:"周杰倫 Jay Chou【明明就 Ming Ming Jiu】Official MV.mp3",artist:"NA",src:"KKBOX_History/周杰倫 Jay Chou【明明就 Ming Ming Jiu】Official MV.mp3"},
{name:"周杰倫 Jay Chou【算什麼男人 What Kind of Man】Official MV (ft. 林依晨).mp3",artist:"NA",src:"KKBOX_History/周杰倫 Jay Chou【算什麼男人 What Kind of Man】Official MV (ft. 林依晨).mp3"},
{name:"周杰倫 Jay Chou【說了再見 Say Goodbye】Official MV.mp3",artist:"NA",src:"KKBOX_History/周杰倫 Jay Chou【說了再見 Say Goodbye】Official MV.mp3"},
{name:"周杰倫 Jay Chou【說好不哭 Won't Cry】with 五月天阿信 (Mayday Ashin) Official MV.mp3",artist:"NA",src:"KKBOX_History/周杰倫 Jay Chou【說好不哭 Won't Cry】with 五月天阿信 (Mayday Ashin) Official MV.mp3"},
{name:"周杰倫&Lara - 珊瑚海 HD.mp3",artist:"NA",src:"KKBOX_History/周杰倫&Lara - 珊瑚海 HD.mp3"},
{name:"周杰倫Jay Chou X aMEI【不該 Shouldn't Be】Official MV.mp3",artist:"NA",src:"KKBOX_History/周杰倫Jay Chou X aMEI【不該 Shouldn't Be】Official MV.mp3"},
{name:"周杰倫Jay Chou(???????)【等你下課Waiting For You】(君?待????).mp3",artist:"NA",src:"KKBOX_History/周杰倫Jay Chou(???????)【等你下課Waiting For You】(君?待????).mp3"},
{name:"周湯豪 NICKTHEREAL《帥到分手》Official Music Video [飛魚高校生 片頭曲].mp3",artist:"NA",src:"KKBOX_History/周湯豪 NICKTHEREAL《帥到分手》Official Music Video [飛魚高校生 片頭曲].mp3"},
{name:"林凡 Freya Lim【歲月這把刀 Time doesn't heal】三立優質偶像劇 《女人30情定水舞間》片尾曲 Official Music Video.mp3",artist:"NA",src:"KKBOX_History/林凡 Freya Lim【歲月這把刀 Time doesn't heal】三立優質偶像劇 《女人30情定水舞間》片尾曲 Official Music Video.mp3"},
{name:"林京燁(Kim) '妮妮(NiNI) ' Official music video ｜那對夫妻 (Nico&Kim&Nini).mp3",artist:"NA",src:"KKBOX_History/林京燁(Kim) '妮妮(NiNI) ' Official music video ｜那對夫妻 (Nico&Kim&Nini).mp3"},
{name:"林俊傑 JJ Lin – 不為誰而作的歌 Twilight (華納 Official 高畫質 HD 官方完整版 MV).mp3",artist:"NA",src:"KKBOX_History/林俊傑 JJ Lin – 不為誰而作的歌 Twilight (華納 Official 高畫質 HD 官方完整版 MV).mp3"},
{name:"林俊傑 JJ Lin - 可惜沒如果 If Only (華納 Official 高畫質 HD 官方劇情版 MV).mp3",artist:"NA",src:"KKBOX_History/林俊傑 JJ Lin - 可惜沒如果 If Only (華納 Official 高畫質 HD 官方劇情版 MV).mp3"},
{name:"林俊傑 JJ Lin - 修煉愛情 Practice Love (華納official 高畫質HD官方完整版MV).mp3",artist:"NA",src:"KKBOX_History/林俊傑 JJ Lin - 修煉愛情 Practice Love (華納official 高畫質HD官方完整版MV).mp3"},
{name:"林俊傑 JJ Lin - 黑夜問白天 53? ?Dawns (華納 Official HD 官方MV).mp3",artist:"NA",src:"KKBOX_History/林俊傑 JJ Lin - 黑夜問白天 53? ?Dawns (華納 Official HD 官方MV).mp3"},
{name:"林俊傑 JJ Lin - 學不會 Never Learn (官方完整 HD 高畫質版 MV).mp3",artist:"NA",src:"KKBOX_History/林俊傑 JJ Lin - 學不會 Never Learn (官方完整 HD 高畫質版 MV).mp3"},
{name:"林俊傑 JJ Lin【原來 Truth】官方完整版 MV.mp3",artist:"NA",src:"KKBOX_History/林俊傑 JJ Lin【原來 Truth】官方完整版 MV.mp3"},
{name:"林俊傑 JJ Lin【曹操 CaoCao】官方完整版 MV.mp3",artist:"NA",src:"KKBOX_History/林俊傑 JJ Lin【曹操 CaoCao】官方完整版 MV.mp3"},
{name:"林宥嘉 Yoga Lin [說謊 Fairy Tale] Official MV.mp3",artist:"NA",src:"KKBOX_History/林宥嘉 Yoga Lin [說謊 Fairy Tale] Official MV.mp3"},
{name:"阿冗 - 與我無關【動態歌詞】「望眼欲穿 等不到你的晚安」?.mp3",artist:"NA",src:"KKBOX_History/阿冗 - 與我無關【動態歌詞】「望眼欲穿 等不到你的晚安」?.mp3"},
{name:"阿拉斯加海灣- 菲道? Cover ( 蔡恩雨 Priscilla Abby).mp3",artist:"NA",src:"KKBOX_History/阿拉斯加海灣- 菲道? Cover ( 蔡恩雨 Priscilla Abby).mp3"},
{name:"?奕迅 - ?情?移 MV.mp3",artist:"NA",src:"KKBOX_History/?奕迅 - ?情?移 MV.mp3"},
{name:"南拳媽媽 - 下雨天.mp3",artist:"NA",src:"KKBOX_History/南拳媽媽 - 下雨天.mp3"},
{name:"范瑋琪 - 一個像夏天一個像秋天.mp3",artist:"NA",src:"KKBOX_History/范瑋琪 - 一個像夏天一個像秋天.mp3"},
{name:"范瑋琪 Christine Fan - 灰色的彩虹 (官方版MV).mp3",artist:"NA",src:"KKBOX_History/范瑋琪 Christine Fan - 灰色的彩虹 (官方版MV).mp3"},
{name:"范瑋琪 Christine Fan - 是非題 (官方版MV).mp3",artist:"NA",src:"KKBOX_History/范瑋琪 Christine Fan - 是非題 (官方版MV).mp3"},
{name:"范瑋琪 Christine Fan - 想知道現在你好不好 (官方版MV).mp3",artist:"NA",src:"KKBOX_History/范瑋琪 Christine Fan - 想知道現在你好不好 (官方版MV).mp3"},
{name:"茄子蛋EggPlantEgg - 愛情你比我想的閣較偉大 (Official Music Video)《當男人戀愛時》電影主題曲.mp3",artist:"NA",src:"KKBOX_History/茄子蛋EggPlantEgg - 愛情你比我想的閣較偉大 (Official Music Video)《當男人戀愛時》電影主題曲.mp3"},
{name:"郁可唯 Yisa Yu【指望】台視、三立偶像劇「犀利人妻」插曲 Official Music Video.mp3",artist:"NA",src:"KKBOX_History/郁可唯 Yisa Yu【指望】台視、三立偶像劇「犀利人妻」插曲 Official Music Video.mp3"},
{name:"郁可唯 Yisa Yu【微加幸福】台視、三立華劇「小資女孩向前衝」片尾曲 Official Music Video.mp3",artist:"NA",src:"KKBOX_History/郁可唯 Yisa Yu【微加幸福】台視、三立華劇「小資女孩向前衝」片尾曲 Official Music Video.mp3"},
{name:"韋禮安 Weibird Wei - 因為愛 (官方版MV) - 民視偶像劇「星座愛情」水瓶女插曲.mp3",artist:"NA",src:"KKBOX_History/韋禮安 Weibird Wei - 因為愛 (官方版MV) - 民視偶像劇「星座愛情」水瓶女插曲.mp3"},
{name:"夏至未至 Rush to the Dead Summer 插曲《追光者》岑寧兒.mp3",artist:"NA",src:"KKBOX_History/夏至未至 Rush to the Dead Summer 插曲《追光者》岑寧兒.mp3"},
{name:"孫燕姿 Yanzi Sun - 我懷念的 What I Miss (official官方完整版MV).mp3",artist:"NA",src:"KKBOX_History/孫燕姿 Yanzi Sun - 我懷念的 What I Miss (official官方完整版MV).mp3"},
{name:"孫燕姿 YanZi Sun– 克卜勒 (Official Music Video).mp3",artist:"NA",src:"KKBOX_History/孫燕姿 YanZi Sun– 克卜勒 (Official Music Video).mp3"},
{name:"徐佳瑩 LaLa【尋人啟事】[HD]Official Music Video.mp3",artist:"NA",src:"KKBOX_History/徐佳瑩 LaLa【尋人啟事】[HD]Official Music Video.mp3"},
{name:"徐若瑄 - 好眼淚壞眼淚 MV  （特別演出：唐禹哲）.mp3",artist:"NA",src:"KKBOX_History/徐若瑄 - 好眼淚壞眼淚 MV  （特別演出：唐禹哲）.mp3"},
{name:"真音樂現場 蕭敬騰 3 世界唯一的你.mp3",artist:"NA",src:"KKBOX_History/真音樂現場 蕭敬騰 3 世界唯一的你.mp3"},
{name:"逆光自製MV.mp3",artist:"NA",src:"KKBOX_History/逆光自製MV.mp3"},
{name:"高爾宣 OSN -【So Bad】Official MV.mp3",artist:"NA",src:"KKBOX_History/高爾宣 OSN -【So Bad】Official MV.mp3"},
{name:"高爾宣 OSN -【Without You】沒了妳｜Official MV.mp3",artist:"NA",src:"KKBOX_History/高爾宣 OSN -【Without You】沒了妳｜Official MV.mp3"},
{name:"庾澄慶 Harlem Yu - 無盡透明的思念 (官方版MV).mp3",artist:"NA",src:"KKBOX_History/庾澄慶 Harlem Yu - 無盡透明的思念 (官方版MV).mp3"},
{name:"張芸京 Jing Chang-  愛情選項 (官方完整版MV).mp3",artist:"NA",src:"KKBOX_History/張芸京 Jing Chang-  愛情選項 (官方完整版MV).mp3"},
{name:"張芸京 Jing Chang - 壞了 Broken (官方完整版MV).mp3",artist:"NA",src:"KKBOX_History/張芸京 Jing Chang - 壞了 Broken (官方完整版MV).mp3"},
{name:"張惠妹 A-Mei -  一眼瞬間 A Moment (official官方完整版MV).mp3",artist:"NA",src:"KKBOX_History/張惠妹 A-Mei -  一眼瞬間 A Moment (official官方完整版MV).mp3"},
{name:"張惠妹 A-Mei - 人質 Hostage (official 官方完整版MV).mp3",artist:"NA",src:"KKBOX_History/張惠妹 A-Mei - 人質 Hostage (official 官方完整版MV).mp3"},
{name:"張惠妹 A-Mei - 我要快樂？I Want Happiness (official 官方完整版MV).mp3",artist:"NA",src:"KKBOX_History/張惠妹 A-Mei - 我要快樂？I Want Happiness (official 官方完整版MV).mp3"},
{name:"張惠妹 A-Mei - 我最親愛的 My Dearest (official官方完整版MV).mp3",artist:"NA",src:"KKBOX_History/張惠妹 A-Mei - 我最親愛的 My Dearest (official官方完整版MV).mp3"},
{name:"張惠妹A-Mei - 如果你也聽說 Have You Heard Lately (official官方完整版MV).mp3",artist:"NA",src:"KKBOX_History/張惠妹A-Mei - 如果你也聽說 Have You Heard Lately (official官方完整版MV).mp3"},
{name:"張棟樑 Nicholas Teo -  寂寞邊界 Loneliness (官方完整KARAOKE版MV).mp3",artist:"NA",src:"KKBOX_History/張棟樑 Nicholas Teo -  寂寞邊界 Loneliness (官方完整KARAOKE版MV).mp3"},
{name:"張韶涵 Angela Zhang - 不痛 (官方版MV).mp3",artist:"NA",src:"KKBOX_History/張韶涵 Angela Zhang - 不痛 (官方版MV).mp3"},
{name:"張韶涵 Angela Zhang - 不想懂得 (官方版MV).mp3",artist:"NA",src:"KKBOX_History/張韶涵 Angela Zhang - 不想懂得 (官方版MV).mp3"},
{name:"張韶涵 Angela Zhang - 白白的 (官方版MV).mp3",artist:"NA",src:"KKBOX_History/張韶涵 Angela Zhang - 白白的 (官方版MV).mp3"},
{name:"張韶涵 Angela Zhang - 看得最遠的地方 (官方版MV).mp3",artist:"NA",src:"KKBOX_History/張韶涵 Angela Zhang - 看得最遠的地方 (官方版MV).mp3"},
{name:"張韶涵 Angela Zhang - 親愛的那不是愛情 (官方版MV).mp3",artist:"NA",src:"KKBOX_History/張韶涵 Angela Zhang - 親愛的那不是愛情 (官方版MV).mp3"},
{name:"曹格 Gary Chaw【背叛】Official Music Video.mp3",artist:"NA",src:"KKBOX_History/曹格 Gary Chaw【背叛】Official Music Video.mp3"},
{name:"曹格 Gary Chaw【無辜】Official Music Video.mp3",artist:"NA",src:"KKBOX_History/曹格 Gary Chaw【無辜】Official Music Video.mp3"},
{name:"梁文音Wen Yin Liang – 分手後不要做朋友 (Lyric Video).mp3",artist:"NA",src:"KKBOX_History/梁文音Wen Yin Liang – 分手後不要做朋友 (Lyric Video).mp3"},
{name:"梁靜茹 Fish Leong – 愛久見人心 (Official Music Video).mp3",artist:"NA",src:"KKBOX_History/梁靜茹 Fish Leong – 愛久見人心 (Official Music Video).mp3"},
{name:"梁靜茹-沒有如果 MV(480P).mp3",artist:"NA",src:"KKBOX_History/梁靜茹-沒有如果 MV(480P).mp3"},
{name:"終極一班2電視原聲帶 - 一個人想著一個人(曾沛慈 - 華納 official HD 完整版 MV).mp3",artist:"NA",src:"KKBOX_History/終極一班2電視原聲帶 - 一個人想著一個人(曾沛慈 - 華納 official HD 完整版 MV).mp3"},
{name:"郭采潔 又圓了的月亮 -華納official HQ官方版MV.mp3",artist:"NA",src:"KKBOX_History/郭采潔 又圓了的月亮 -華納official HQ官方版MV.mp3"},
{name:"郭書瑤《幸福不遠》Official 完整版 MV [HD].mp3",artist:"NA",src:"KKBOX_History/郭書瑤《幸福不遠》Official 完整版 MV [HD].mp3"},
{name:"郭靜 Claire Kuo - Encore LaLa (官方版MV).mp3",artist:"NA",src:"KKBOX_History/郭靜 Claire Kuo - Encore LaLa (官方版MV).mp3"},
{name:"郭靜 Claire Kuo - 下一個天亮 (官方版MV).mp3",artist:"NA",src:"KKBOX_History/郭靜 Claire Kuo - 下一個天亮 (官方版MV).mp3"},
{name:"郭靜 Claire Kuo - 心牆 (官方版MV).mp3",artist:"NA",src:"KKBOX_History/郭靜 Claire Kuo - 心牆 (官方版MV).mp3"},
{name:"郭靜 Claire Kuo - 在樹上唱歌 (官方版MV).mp3",artist:"NA",src:"KKBOX_History/郭靜 Claire Kuo - 在樹上唱歌 (官方版MV).mp3"},
{name:"郭靜 Claire Kuo - 我不想忘記你 (官方版MV).mp3",artist:"NA",src:"KKBOX_History/郭靜 Claire Kuo - 我不想忘記你 (官方版MV).mp3"},
{name:"郭靜 Claire Kuo - 聊天 (官方版MV).mp3",artist:"NA",src:"KKBOX_History/郭靜 Claire Kuo - 聊天 (官方版MV).mp3"},
{name:"郭靜 Claire Kuo - 嫁妝 (官方版MV).mp3",artist:"NA",src:"KKBOX_History/郭靜 Claire Kuo - 嫁妝 (官方版MV).mp3"},
{name:"陳小春 Jordan Chan – 獨家記憶 (Official Music Video).mp3",artist:"NA",src:"KKBOX_History/陳小春 Jordan Chan – 獨家記憶 (Official Music Video).mp3"},
{name:"陳奕迅 - 淘汰 HD.mp3",artist:"NA",src:"KKBOX_History/陳奕迅 - 淘汰 HD.mp3"},
{name:"陳勢安 Andrew Tan + 畢書盡 Bii - 勢在必行 (官方版MV).mp3",artist:"NA",src:"KKBOX_History/陳勢安 Andrew Tan + 畢書盡 Bii - 勢在必行 (官方版MV).mp3"},
{name:"韓庚 - My Logo.mp3",artist:"NA",src:"KKBOX_History/?庚 - My Logo.mp3"},
{name:"黃小琥 沒那麼簡單- 華納official HQ官方版MV.mp3",artist:"NA",src:"KKBOX_History/黃小琥 沒那麼簡單- 華納official HQ官方版MV.mp3"},
{name:"黃立行 Stanley Huang - 無神論  (華納official 官方完整版MV).mp3",artist:"NA",src:"KKBOX_History/黃立行 Stanley Huang - 無神論  (華納official 官方完整版MV).mp3"},
{name:"黃明志 Ft. 王力宏【漂向北方】@亞洲通車 2016 Crossover Asia.mp3",artist:"NA",src:"KKBOX_History/黃明志 Ft. 王力宏【漂向北方】@亞洲通車 2016 Crossover Asia.mp3"},
{name:"黃鴻升 Alien Huang 柯有倫 Alan Kuo 竇智孔 Bobby Dou 【扛得住 Carry On】Official Music Video.mp3",artist:"NA",src:"KKBOX_History/黃鴻升 Alien Huang 柯有倫 Alan Kuo 竇智孔 Bobby Dou 【扛得住 Carry On】Official Music Video.mp3"},
{name:"黃鴻升 Alien Huang【地球上最浪漫的一首歌】Official Music Video.mp3",artist:"NA",src:"KKBOX_History/黃鴻升 Alien Huang【地球上最浪漫的一首歌】Official Music Video.mp3"},
{name:"新文字文件.bat",artist:"NA",src:"KKBOX_History/新文字文件.bat"},
{name:"楊丞琳 Rainie Yang - 我們都傻.mp3",artist:"NA",src:"KKBOX_History/楊丞琳 Rainie Yang - 我們都傻.mp3"},
{name:"楊丞琳 Rainie Yang - 雨愛.mp3",artist:"NA",src:"KKBOX_History/楊丞琳 Rainie Yang - 雨愛.mp3"},
{name:"楊丞琳 Rainie Yang - 曖昧.mp3",artist:"NA",src:"KKBOX_History/楊丞琳 Rainie Yang - 曖昧.mp3"},
{name:"楊丞琳 過敏 (Official Video Karaoke).mp3",artist:"NA",src:"KKBOX_History/楊丞琳 過敏 (Official Video Karaoke).mp3"},
{name:"楊丞琳Rainie Yang - 失憶的金魚 (Official HD MV).mp3",artist:"NA",src:"KKBOX_History/楊丞琳Rainie Yang - 失憶的金魚 (Official HD MV).mp3"},
{name:"楊丞琳Rainie Yang - 勇敢很好Brave Love (HD互動式MV).mp3",artist:"NA",src:"KKBOX_History/楊丞琳Rainie Yang - 勇敢很好Brave Love (HD互動式MV).mp3"},
{name:"楊宗緯 Aska Yang [ 多餘 (愛 星光精選 [昨天今天明天] )] Official Music Video.mp3",artist:"NA",src:"KKBOX_History/楊宗緯 Aska Yang [ 多餘 (愛 星光精選 [昨天今天明天] )] Official Music Video.mp3"},
{name:"劉若英 [ 我不想念 ] MV官方完整高清版.mp3",artist:"NA",src:"KKBOX_History/劉若英 [ 我不想念 ] MV官方完整高清版.mp3"},
{name:"劉若英 [ 我們沒有在一起 ] MV官方完整版.mp3",artist:"NA",src:"KKBOX_History/劉若英 [ 我們沒有在一起 ] MV官方完整版.mp3"},
{name:"瘦子E.SO【CHANGE】Official Music Video(5K).mp3",artist:"NA",src:"KKBOX_History/瘦子E.SO【CHANGE】Official Music Video(5K).mp3"},
{name:"瘦子E.SO【太陽 When The Cloudless Day Comes】Lyric Video.mp3",artist:"NA",src:"KKBOX_History/瘦子E.SO【太陽 When The Cloudless Day Comes】Lyric Video.mp3"},
{name:"瘦子E.SO【她沒在看我 She Ain’t Watchin’】Official Music Video(5K).mp3",artist:"NA",src:"KKBOX_History/瘦子E.SO【她沒在看我 She Ain’t Watchin’】Official Music Video(5K).mp3"},
{name:"蔡依林 Jolin Tsai -  特務J  (華納official 官方完整版MV).mp3",artist:"NA",src:"KKBOX_History/蔡依林 Jolin Tsai -  特務J  (華納official 官方完整版MV).mp3"},
{name:"蔡依林 Jolin Tsai -  假裝 (華納official 官方完整版MV).mp3",artist:"NA",src:"KKBOX_History/蔡依林 Jolin Tsai -  假裝 (華納official 官方完整版MV).mp3"},
{name:"蔡依林 Jolin Tsai -  舞孃  (華納official 官方完整版MV).mp3",artist:"NA",src:"KKBOX_History/蔡依林 Jolin Tsai -  舞孃  (華納official 官方完整版MV).mp3"},
{name:"蔡依林 Jolin Tsai - 大藝術家The Great Artist (華納official 高畫質HD官方完整版MV).mp3",artist:"NA",src:"KKBOX_History/蔡依林 Jolin Tsai - 大藝術家The Great Artist (華納official 高畫質HD官方完整版MV).mp3"},
{name:"蔡依林 Jolin Tsai - 馬德里不思議 A Wonder In Madrid (華納official 官方完整版MV).mp3",artist:"NA",src:"KKBOX_History/蔡依林 Jolin Tsai - 馬德里不思議 A Wonder In Madrid (華納official 官方完整版MV).mp3"},
{name:"蔡依林 Jolin Tsai - 第三人稱 The Third Person And I (華納official 高畫質HD官方完整版MV).mp3",artist:"NA",src:"KKBOX_History/蔡依林 Jolin Tsai - 第三人稱 The Third Person And I (華納official 高畫質HD官方完整版MV).mp3"},
{name:"蔡依林 Jolin Tsai -詩人漫步Wandering Poet (華納official 高畫質HD官方完整版MV).mp3",artist:"NA",src:"KKBOX_History/蔡依林 Jolin Tsai -詩人漫步Wandering Poet (華納official 高畫質HD官方完整版MV).mp3"},
{name:"蔡依林 Jolin Tsai《怪美的 UGLY BEAUTY》Official Music Video.mp3",artist:"NA",src:"KKBOX_History/蔡依林 Jolin Tsai《怪美的 UGLY BEAUTY》Official Music Video.mp3"},
{name:"盧廣仲 Crowd Lu 【刻在我心底的名字 Your Name Engraved Herein】 Official Music Video  （刻在你心底的名字電影主題曲）.mp3",artist:"NA",src:"KKBOX_History/盧廣仲 Crowd Lu 【刻在我心底的名字 Your Name Engraved Herein】 Official Music Video  （刻在你心底的名字電影主題曲）.mp3"},
{name:"盧廣仲 Crowd Lu 【魚仔】 Official Music Video （花甲男孩轉大人主題曲）.mp3",artist:"NA",src:"KKBOX_History/盧廣仲 Crowd Lu 【魚仔】 Official Music Video （花甲男孩轉大人主題曲）.mp3"},
{name:"蕭亞軒 Elva Hsiao - 逞強 Stubborn (官方完整版MV).mp3",artist:"NA",src:"KKBOX_History/蕭亞軒 Elva Hsiao - 逞強 Stubborn (官方完整版MV).mp3"},
{name:"蕭亞軒Elva Hsiao – SUPER GIRL 愛無畏 (Official HD MV).mp3",artist:"NA",src:"KKBOX_History/蕭亞軒Elva Hsiao – SUPER GIRL 愛無畏 (Official HD MV).mp3"},
{name:"蕭秉治 Xiao Bing Chih [ 愛過你有多久就有多痛 Love Hurts ] Official Music Video.mp3",artist:"NA",src:"KKBOX_History/蕭秉治 Xiao Bing Chih [ 愛過你有多久就有多痛 Love Hurts ] Official Music Video.mp3"},
{name:"蕭敬騰 - 王子的新衣【官方完整版 Official Music Video】.mp3",artist:"NA",src:"KKBOX_History/蕭敬騰 - 王子的新衣【官方完整版 Official Music Video】.mp3"},
{name:"蕭敬騰 - 收藏【官方完整版 Official Music Video】.mp3",artist:"NA",src:"KKBOX_History/蕭敬騰 - 收藏【官方完整版 Official Music Video】.mp3"},
{name:"蕭敬騰 王妃-華納official HQ官方版MV.mp3",artist:"NA",src:"KKBOX_History/蕭敬騰 王妃-華納official HQ官方版MV.mp3"},
{name:"蕭敬騰 善男信女MV.mp3",artist:"NA",src:"KKBOX_History/蕭敬騰 善男信女MV.mp3"},
{name:"蕭敬騰 無言花-華納official HQ官方版MV.mp3",artist:"NA",src:"KKBOX_History/蕭敬騰 無言花-華納official HQ官方版MV.mp3"},
{name:"蕭敬騰 新不了情-華納official HQ官方版MV.mp3",artist:"NA",src:"KKBOX_History/蕭敬騰 新不了情-華納official HQ官方版MV.mp3"},
{name:"蕭敬騰洛克先生演唱會Live紀實-童話.mp3",artist:"NA",src:"KKBOX_History/蕭敬騰洛克先生演唱會Live紀實-童話.mp3"},
{name:"親親 - 梁靜如.mp3",artist:"NA",src:"KKBOX_History/親親 - 梁靜如.mp3"},
{name:"戴愛玲 Princess Ai - 空港 Official Music Video.mp3",artist:"NA",src:"KKBOX_History/戴愛玲 Princess Ai - 空港 Official Music Video.mp3"},
{name:"戴愛玲 Princess Ai Tai - 累格.mp3",artist:"NA",src:"KKBOX_History/戴愛玲 Princess Ai Tai - 累格.mp3"},
{name:"謝和弦 R-chord – 愛不需要裝乖 Love Doesn't Need To Pretend feat. 王詩安 Diana(華納 Official 高畫質 HD 官方完整版 MV).mp3",artist:"NA",src:"KKBOX_History/謝和弦 R-chord – 愛不需要裝乖 Love Doesn't Need To Pretend feat. 王詩安 Diana(華納 Official 高畫質 HD 官方完整版 MV).mp3"},
{name:"謝和弦 R-chord – 謝謝妳愛我 Thanks for your love (華納 Official 高畫質 HD 官方完整版 MV).mp3",artist:"NA",src:"KKBOX_History/謝和弦 R-chord – 謝謝妳愛我 Thanks for your love (華納 Official 高畫質 HD 官方完整版 MV).mp3"},
{name:"羅志祥 - 愛轉角 MV.mp3",artist:"NA",src:"KKBOX_History/羅志祥 - 愛轉角 MV.mp3"},
{name:"羅志祥 Show Lo  - 搞笑 Hide Behind Smile  (官方完整版MV).mp3",artist:"NA",src:"KKBOX_History/羅志祥 Show Lo  - 搞笑 Hide Behind Smile  (官方完整版MV).mp3"},
{name:"羅志祥 Show Lo - 我不會唱歌 A Song For You (官方完整版MV).mp3",artist:"NA",src:"KKBOX_History/羅志祥 Show Lo - 我不會唱歌 A Song For You (官方完整版MV).mp3"},
{name:"羅志祥 Show Lo - 愛不單行 You Won't Be Alone (官方完整版MV).mp3",artist:"NA",src:"KKBOX_History/羅志祥 Show Lo - 愛不單行 You Won't Be Alone (官方完整版MV).mp3"},
{name:"羅志祥Show Lo - 不具名的悲傷Anonymous Sadness (Official HD MV).mp3",artist:"NA",src:"KKBOX_History/羅志祥Show Lo - 不具名的悲傷Anonymous Sadness (Official HD MV).mp3"},
{name:"羅志祥Show Lo - 空中飛人Flyer(Official HD MV).mp3",artist:"NA",src:"KKBOX_History/羅志祥Show Lo - 空中飛人Flyer(Official HD MV).mp3"},

]
