trackList = 
[
{name:"( 歌詞 ) 五月天 - 天使.mp3",artist:"NA",src:"70_80_typical/( 歌詞 ) 五月天 - 天使.mp3"},
{name:"[avex官方] A-Lin 失戀無罪 (MV完整版).mp3",artist:"NA",src:"70_80_typical/[avex官方] A-Lin 失戀無罪 (MV完整版).mp3"},
{name:"[avex官方] A-Lin 給我一個理由忘記 (MV完整版).mp3",artist:"NA",src:"70_80_typical/[avex官方] A-Lin 給我一個理由忘記 (MV完整版).mp3"},
{name:"[avex官方] dance flow – 迷人的危險 (官方完整版MV).mp3",artist:"NA",src:"70_80_typical/[avex官方] dance flow – 迷人的危險 (官方完整版MV).mp3"},
{name:"[avex官方]伍佰 & China Blue 妳是我的花朵(MV完整版).mp3",artist:"NA",src:"70_80_typical/[avex官方]伍佰 & China Blue 妳是我的花朵(MV完整版).mp3"},
{name:"[avex官方]羅志祥 精舞門 (MV完整版).mp3",artist:"NA",src:"70_80_typical/[avex官方]羅志祥 精舞門 (MV完整版).mp3"},
{name:"[avex官方]羅志祥 戀愛達人 (MV完整版).mp3",artist:"NA",src:"70_80_typical/[avex官方]羅志祥 戀愛達人 (MV完整版).mp3"},
{name:"[JOY RICH] [舊歌] 徐若瑄 - 愛笑的眼睛.mp3",artist:"NA",src:"70_80_typical/[JOY RICH] [舊歌] 徐若瑄 - 愛笑的眼睛.mp3"},
{name:"[JOY RICH] [舊歌] 陳小春 - 我愛的人(周杰倫作曲).mp3",artist:"NA",src:"70_80_typical/[JOY RICH] [舊歌] 陳小春 - 我愛的人(周杰倫作曲).mp3"},
{name:"[JOY RICH] [舊歌] 蕭亞軒 - 錯的人.mp3",artist:"NA",src:"70_80_typical/[JOY RICH] [舊歌] 蕭亞軒 - 錯的人.mp3"},
{name:"[KTV] 孫燕姿 - 遇見.mp3",artist:"NA",src:"70_80_typical/[KTV] 孫燕姿 - 遇見.mp3"},
{name:"[KTV]南拳媽媽-橘子汽水.mp3",artist:"NA",src:"70_80_typical/[KTV]南拳媽媽-橘子汽水.mp3"},
{name:"[KTV]張芯瑜-雨季開始了-揚聲.mpg.mp3",artist:"NA",src:"70_80_typical/[KTV]張芯瑜-雨季開始了-揚聲.mpg.mp3"},
{name:"《無賴正義》 MV.mp3",artist:"NA",src:"70_80_typical/《無賴正義》 MV.mp3"},
{name:"〔MV〕郁可唯 微加幸福.mp3",artist:"NA",src:"70_80_typical/〔MV〕郁可唯 微加幸福.mp3"},
{name:"★手牽手ＭＶ - 抗SARS藝人大合唱★-Hand in Hand-Taiwanese song.mp3",artist:"NA",src:"70_80_typical/★手牽手ＭＶ - 抗SARS藝人大合唱★-Hand in Hand-Taiwanese song.mp3"},
{name:"?   柯受良  吳宗憲  劉德華 ~ 笨小孩  ?.mp3",artist:"NA",src:"70_80_typical/?   柯受良  吳宗憲  劉德華 ~ 笨小孩  ?.mp3"},
{name:"183 CLUB - 完美情人MV.mp3",artist:"NA",src:"70_80_typical/183 CLUB - 完美情人MV.mp3"},
{name:"183club 真愛.mp3",artist:"NA",src:"70_80_typical/183club 真愛.mp3"},
{name:"4 In Love - 一千零一個願望.mp3",artist:"NA",src:"70_80_typical/4 In Love - 一千零一個願望.mp3"},
{name:"4 In Love - 誰怕誰.mp3",artist:"NA",src:"70_80_typical/4 In Love - 誰怕誰.mp3"},
{name:"5566 - 白色花漾 MV [HQ].mp3",artist:"NA",src:"70_80_typical/5566 - 白色花漾 MV [HQ].mp3"},
{name:"5566 - 存在 MV [HQ].mp3",artist:"NA",src:"70_80_typical/5566 - 存在 MV [HQ].mp3"},
{name:"5566 - 我難過 I'm Sad MV [HQ].mp3",artist:"NA",src:"70_80_typical/5566 - 我難過 I'm Sad MV [HQ].mp3"},
{name:"5566【MVP情人】無所謂 MV.mp3",artist:"NA",src:"70_80_typical/5566【MVP情人】無所謂 MV.mp3"},
{name:"5566【紫禁之巔】風雲變色 MV.mp3",artist:"NA",src:"70_80_typical/5566【紫禁之巔】風雲變色 MV.mp3"},
{name:"a MEI 【跳進來JUMP IN】 Official  MV.mp3",artist:"NA",src:"70_80_typical/a MEI 【跳進來JUMP IN】 Official  MV.mp3"},
{name:"A-Do Persevere 阿杜 堅持到底 [All the way].mp3",artist:"NA",src:"70_80_typical/A-Do Persevere 阿杜 堅持到底 [All the way].mp3"},
{name:"Andrew Tan @ ??安 天后 MV.mp3",artist:"NA",src:"70_80_typical/Andrew Tan @ ??安 天后 MV.mp3"},
{name:"B.A.D - Don’t say goodbye (官方完整版MV).mp3",artist:"NA",src:"70_80_typical/B.A.D - Don’t say goodbye (官方完整版MV).mp3"},
{name:"B.A.D - Oh! I  (官方完整版MV).mp3",artist:"NA",src:"70_80_typical/B.A.D - Oh! I  (官方完整版MV).mp3"},
{name:"B.A.D - 我的錯(字幕).mp3",artist:"NA",src:"70_80_typical/B.A.D - 我的錯(字幕).mp3"},
{name:"B.A.D-我的錯(KTV).mp3",artist:"NA",src:"70_80_typical/B.A.D-我的錯(KTV).mp3"},
{name:"B.o.B feat. Bruno Mars - Nothing on you - Cover by 阿福.mp3",artist:"NA",src:"70_80_typical/B.o.B feat. Bruno Mars - Nothing on you - Cover by 阿福.mp3"},
{name:"By2【愛上你 Lovin' U】官方完整版 MV（專輯：成人禮）.mp3",artist:"NA",src:"70_80_typical/By2【愛上你 Lovin' U】官方完整版 MV（專輯：成人禮）.mp3"},
{name:"Chinese Song- 雨蝶.mp3",artist:"NA",src:"70_80_typical/Chinese Song- 雨蝶.mp3"},
{name:"Cindy袁詠琳【畫沙 Sand Painting】Official MV (ft. @周杰倫 Jay Chou ).mp3",artist:"NA",src:"70_80_typical/Cindy袁詠琳【畫沙 Sand Painting】Official MV (ft. @周杰倫 Jay Chou ).mp3"},
{name:"Come On.mp3",artist:"NA",src:"70_80_typical/Come On.mp3"},
{name:"Cyndi Wang 王心凌 - Ai Ni 愛你.mp3",artist:"NA",src:"70_80_typical/Cyndi Wang 王心凌 - Ai Ni 愛你.mp3"},
{name:"Della丁噹 [ 洋蔥 ] MV官方高清完整版.mp3",artist:"NA",src:"70_80_typical/Della丁噹 [ 洋蔥 ] MV官方高清完整版.mp3"},
{name:"Della丁噹【不是你的錯Not Your Fault】MV官方完整版-三立[真愛找麻煩]插曲.mp3",artist:"NA",src:"70_80_typical/Della丁噹【不是你的錯Not Your Fault】MV官方完整版-三立[真愛找麻煩]插曲.mp3"},
{name:"Energy【某年某月某一天】HQ.mp3",artist:"NA",src:"70_80_typical/Energy【某年某月某一天】HQ.mp3"},
{name:"ENERGY多愛我一天.mp3",artist:"NA",src:"70_80_typical/ENERGY多愛我一天.mp3"},
{name:"F.I.R. 飛兒樂團 - Lydia (official 官方完整版MV).mp3",artist:"NA",src:"70_80_typical/F.I.R. 飛兒樂團 - Lydia (official 官方完整版MV).mp3"},
{name:"F.I.R. 飛兒樂團 - 千年之戀 (official 官方完整版MV).mp3",artist:"NA",src:"70_80_typical/F.I.R. 飛兒樂團 - 千年之戀 (official 官方完整版MV).mp3"},
{name:"F.I.R. 飛兒樂團 - 月牙灣 Crescent Bay (official 官方完整版MV).mp3",artist:"NA",src:"70_80_typical/F.I.R. 飛兒樂團 - 月牙灣 Crescent Bay (official 官方完整版MV).mp3"},
{name:"F.I.R. 飛兒樂團 - 你的微笑 (official 官方完整版MV).mp3",artist:"NA",src:"70_80_typical/F.I.R. 飛兒樂團 - 你的微笑 (official 官方完整版MV).mp3"},
{name:"F.I.R. 飛兒樂團 - 我們的愛 (official官方完整版MV).mp3",artist:"NA",src:"70_80_typical/F.I.R. 飛兒樂團 - 我們的愛 (official官方完整版MV).mp3"},
{name:"F4 - 流星雨.mp3",artist:"NA",src:"70_80_typical/F4 - 流星雨.mp3"},
{name:"Jay Chou 周杰倫 [退後 A Step Back] Official Music Video.mp3",artist:"NA",src:"70_80_typical/Jay Chou 周杰倫 [退後 A Step Back] Official Music Video.mp3"},
{name:"Jay Chou 周杰倫【七里香 Qi-Li-Xiang】-Official Music Video.mp3",artist:"NA",src:"70_80_typical/Jay Chou 周杰倫【七里香 Qi-Li-Xiang】-Official Music Video.mp3"},
{name:"Jay Chou 周杰倫【三年二班 Class 3-2】-Official Music Video.mp3",artist:"NA",src:"70_80_typical/Jay Chou 周杰倫【三年二班 Class 3-2】-Official Music Video.mp3"},
{name:"Jay Chou 周杰倫【千里之外 Far Away】-Official Music Video(ft.費玉清).mp3",artist:"NA",src:"70_80_typical/Jay Chou 周杰倫【千里之外 Far Away】-Official Music Video(ft.費玉清).mp3"},
{name:"Jay Chou 周杰倫【不能說的祕密 Secret】-Official Music Video.mp3",artist:"NA",src:"70_80_typical/Jay Chou 周杰倫【不能說的祕密 Secret】-Official Music Video.mp3"},
{name:"Jay Chou 周杰倫【我不配 Not Good Enough For You】-Official Music Video.mp3",artist:"NA",src:"70_80_typical/Jay Chou 周杰倫【我不配 Not Good Enough For You】-Official Music Video.mp3"},
{name:"Jay Chou 周杰倫【星晴 Starry Mood】-Official Music Video.mp3",artist:"NA",src:"70_80_typical/Jay Chou 周杰倫【星晴 Starry Mood】-Official Music Video.mp3"},
{name:"Jay Chou 周杰倫【珊瑚海 Coral Sea】-Official Music Video.mp3",artist:"NA",src:"70_80_typical/Jay Chou 周杰倫【珊瑚海 Coral Sea】-Official Music Video.mp3"},
{name:"Jay Chou 周杰倫【黑色毛衣 Black Sweater】-Official Music Video.mp3",artist:"NA",src:"70_80_typical/Jay Chou 周杰倫【黑色毛衣 Black Sweater】-Official Music Video.mp3"},
{name:"Jay Chou 周杰倫【髮如雪 Hair Like Snow】-Official Music Video.mp3",artist:"NA",src:"70_80_typical/Jay Chou 周杰倫【髮如雪 Hair Like Snow】-Official Music Video.mp3"},
{name:"Jay Chou 周杰倫【霍元甲 Fearless】-Official Music Video.mp3",artist:"NA",src:"70_80_typical/Jay Chou 周杰倫【霍元甲 Fearless】-Official Music Video.mp3"},
{name:"Jay Chou周杰倫【晴天 Sunny Day】-Official Music Video.mp3",artist:"NA",src:"70_80_typical/Jay Chou周杰倫【晴天 Sunny Day】-Official Music Video.mp3"},
{name:"Joi Chua 蔡淳佳 陪我看日出 MVKTV.mp3",artist:"NA",src:"70_80_typical/Joi Chua 蔡淳佳 陪我看日出 MVKTV.mp3"},
{name:"jolin Don't Stop.mp3",artist:"NA",src:"70_80_typical/jolin Don't Stop.mp3"},
{name:"JS-殺破狼(仙劍一片頭曲)-高清原創版.mp3",artist:"NA",src:"70_80_typical/JS-殺破狼(仙劍一片頭曲)-高清原創版.mp3"},
{name:"Khalil Fong (方大同) - 復刻回憶 ft. Fiona Sit (薛凱琪) Official Music Video.mp3",artist:"NA",src:"70_80_typical/Khalil Fong (方大同) - 復刻回憶 ft. Fiona Sit (薛凱琪) Official Music Video.mp3"},
{name:"list.txt",artist:"NA",src:"70_80_typical/list.txt"},
{name:"Mayday五月天【洋蔥Onion】MV官方完整版.mp3",artist:"NA",src:"70_80_typical/Mayday五月天【洋蔥Onion】MV官方完整版.mp3"},
{name:"Mayday五月天＋陳綺貞[私奔到月球] MV官方完整版.mp3",artist:"NA",src:"70_80_typical/Mayday五月天＋陳綺貞[私奔到月球] MV官方完整版.mp3"},
{name:"Melody 殷悅《揮之不去》（華視【星願】陳怡蓉、張天霖、張孝全、夏如芝 主演）官方MV (Official Music Video).mp3",artist:"NA",src:"70_80_typical/Melody 殷悅《揮之不去》（華視【星願】陳怡蓉、張天霖、張孝全、夏如芝 主演）官方MV (Official Music Video).mp3"},
{name:"MP魔幻力量【不按牌理出牌Never Play By The Rules】MV官方完整版-三立[醉後決定愛上你]片頭曲.mp3",artist:"NA",src:"70_80_typical/MP魔幻力量【不按牌理出牌Never Play By The Rules】MV官方完整版-三立[醉後決定愛上你]片頭曲.mp3"},
{name:"Rynn Lim Porting 林宇中 靠岸 [Asian Guy].mp3",artist:"NA",src:"70_80_typical/Rynn Lim Porting 林宇中 靠岸 [Asian Guy].mp3"},
{name:"S.H.E - 最近還好嗎 MV.mp3",artist:"NA",src:"70_80_typical/S.H.E - 最近還好嗎 MV.mp3"},
{name:"S.H.E [ Remember ] Official MV.mp3",artist:"NA",src:"70_80_typical/S.H.E [ Remember ] Official MV.mp3"},
{name:"S.H.E [ Super Star ]  Official MV.mp3",artist:"NA",src:"70_80_typical/S.H.E [ Super Star ]  Official MV.mp3"},
{name:"S.H.E [ 一眼萬年 ] Official Music Video.mp3",artist:"NA",src:"70_80_typical/S.H.E [ 一眼萬年 ] Official Music Video.mp3"},
{name:"S.H.E [ 中國話 Chinese ] Official Music Video.mp3",artist:"NA",src:"70_80_typical/S.H.E [ 中國話 Chinese ] Official Music Video.mp3"},
{name:"S.H.E [ 五月天 Mayday ] Official Music Video.mp3",artist:"NA",src:"70_80_typical/S.H.E [ 五月天 Mayday ] Official Music Video.mp3"},
{name:"S.H.E [花都開好了 Flowers have blossomed] Official Music Video.mp3",artist:"NA",src:"70_80_typical/S.H.E [花都開好了 Flowers have blossomed] Official Music Video.mp3"},
{name:"S.H.E [怎麼辦 What to do ] Official Music Video (偶像劇「花樣少男少女」片頭曲).mp3",artist:"NA",src:"70_80_typical/S.H.E [怎麼辦 What to do ] Official Music Video (偶像劇「花樣少男少女」片頭曲).mp3"},
{name:"S.H.E [星光 Star Light] Official Music Video (真命天女 電視原聲帶).mp3",artist:"NA",src:"70_80_typical/S.H.E [星光 Star Light] Official Music Video (真命天女 電視原聲帶).mp3"},
{name:"S.H.E [美麗新世界 Genesis] Official Music Video.mp3",artist:"NA",src:"70_80_typical/S.H.E [美麗新世界 Genesis] Official Music Video.mp3"},
{name:"S.H.E [愛上你 Loving You] Official Music Video.mp3",artist:"NA",src:"70_80_typical/S.H.E [愛上你 Loving You] Official Music Video.mp3"},
{name:"S.H.E [熱帶雨林 Tropical Rainforest] Official Music Video.mp3",artist:"NA",src:"70_80_typical/S.H.E [熱帶雨林 Tropical Rainforest] Official Music Video.mp3"},
{name:"S.H.E [戀人未滿 Not Yet Lovers] Official Music Video.mp3",artist:"NA",src:"70_80_typical/S.H.E [戀人未滿 Not Yet Lovers] Official Music Video.mp3"},
{name:"Show Lo - 愛瘋頭 (Head Over Heels).mp3",artist:"NA",src:"70_80_typical/Show Lo - 愛瘋頭 (Head Over Heels).mp3"},
{name:"Show Lo - 獨一無二 (Only You).mp3",artist:"NA",src:"70_80_typical/Show Lo - 獨一無二 (Only You).mp3"},
{name:"STEFANIE SUN (孫燕姿) - 原點 (蔡健雅合唱).mp3",artist:"NA",src:"70_80_typical/STEFANIE SUN (孫燕姿) - 原點 (蔡健雅合唱).mp3"},
{name:"SWEETY 曾之喬 劉品言《櫻花草》（偶像劇【米可，GO！】主題曲、【星蘋果樂園】插曲）官方MV (Official Music Video).mp3",artist:"NA",src:"70_80_typical/SWEETY 曾之喬 劉品言《櫻花草》（偶像劇【米可，GO！】主題曲、【星蘋果樂園】插曲）官方MV (Official Music Video).mp3"},
{name:"SWEETY‧ 愛是怎麼一回事.mp3",artist:"NA",src:"70_80_typical/SWEETY‧ 愛是怎麼一回事.mp3"},
{name:"TANK [三國戀 Three Kingdom Love] Official Music Video.mp3",artist:"NA",src:"70_80_typical/TANK [三國戀 Three Kingdom Love] Official Music Video.mp3"},
{name:"TANK [千年淚 Thousand Year Tears] Official MV (電視劇「天外飛仙」片尾曲).mp3",artist:"NA",src:"70_80_typical/TANK [千年淚 Thousand Year Tears] Official MV (電視劇「天外飛仙」片尾曲).mp3"},
{name:"TANK [鬥牛要不要 Hooping Dulcinea] Official MV (偶像劇「 鬥牛要不要」片頭曲).mp3",artist:"NA",src:"70_80_typical/TANK [鬥牛要不要 Hooping Dulcinea] Official MV (偶像劇「 鬥牛要不要」片頭曲).mp3"},
{name:"TANK [專屬天使 Personal Angel] Official Music Video (偶像劇「花樣少男少女」片尾曲).mp3",artist:"NA",src:"70_80_typical/TANK [專屬天使 Personal Angel] Official Music Video (偶像劇「花樣少男少女」片尾曲).mp3"},
{name:"TANK [給我你的愛 Give me your love] Official Music Video.mp3",artist:"NA",src:"70_80_typical/TANK [給我你的愛 Give me your love] Official Music Video.mp3"},
{name:"Tank-非你莫屬 - Audio.mp3",artist:"NA",src:"70_80_typical/Tank-非你莫屬 - Audio.mp3"},
{name:"Tension -  Gotta be your man  (官方完整版MV).mp3",artist:"NA",src:"70_80_typical/Tension -  Gotta be your man  (官方完整版MV).mp3"},
{name:"Tension -  一步一步 (官方完整版MV).mp3",artist:"NA",src:"70_80_typical/Tension -  一步一步 (官方完整版MV).mp3"},
{name:"Tension-《我?的故事》.mp3",artist:"NA",src:"70_80_typical/Tension-《我?的故事》.mp3"},
{name:"Twins《見習愛神》[Official MV].mp3",artist:"NA",src:"70_80_typical/Twins《見習愛神》[Official MV].mp3"},
{name:"Twins《瓶中沙》[MV].mp3",artist:"NA",src:"70_80_typical/Twins《瓶中沙》[MV].mp3"},
{name:"Twins《莫斯科沒有眼淚》[Official MV].mp3",artist:"NA",src:"70_80_typical/Twins《莫斯科沒有眼淚》[Official MV].mp3"},
{name:"Yen-j嚴爵【暫時的男朋友Temporary BF】MV官方完整版.mp3",artist:"NA",src:"70_80_typical/Yen-j嚴爵【暫時的男朋友Temporary BF】MV官方完整版.mp3"},
{name:"ZAYIN-藍色眼睛.mp3",artist:"NA",src:"70_80_typical/ZAYIN-藍色眼睛.mp3"},
{name:"一?子一?? MV.mp3",artist:"NA",src:"70_80_typical/一?子一?? MV.mp3"},
{name:"丁噹 [ 我愛他 ] MV官方完整版.mp3",artist:"NA",src:"70_80_typical/丁噹 [ 我愛他 ] MV官方完整版.mp3"},
{name:"丁噹 猜不透 MV (五月天瑪莎跨刀演出).mp3",artist:"NA",src:"70_80_typical/丁噹 猜不透 MV (五月天瑪莎跨刀演出).mp3"},
{name:"卜學亮(阿亮)（Feat. 曾寶儀）《子曰》官方MV (Official Music Video).mp3",artist:"NA",src:"70_80_typical/卜學亮(阿亮)（Feat. 曾寶儀）《子曰》官方MV (Official Music Video).mp3"},
{name:"上弦月（?志安）.mp3",artist:"NA",src:"70_80_typical/上弦月（?志安）.mp3"},
{name:"大手拉小手.mp3",artist:"NA",src:"70_80_typical/大手拉小手.mp3"},
{name:"大嘴巴 結果咧.mp3",artist:"NA",src:"70_80_typical/大嘴巴 結果咧.mp3"},
{name:"大嘴巴DM 永遠在身邊 官方完整版MV.mp3",artist:"NA",src:"70_80_typical/大嘴巴DM 永遠在身邊 官方完整版MV.mp3"},
{name:"小宇(宋念宇) - 終於說出口「高音質 x 動態歌詞 Lyrics」? SDPMusic ?.mp3",artist:"NA",src:"70_80_typical/小宇(宋念宇) - 終於說出口「高音質 x 動態歌詞 Lyrics」? SDPMusic ?.mp3"},
{name:"小薰 + 阿本 - 甜甜圈 (官方版MV).mp3",artist:"NA",src:"70_80_typical/小薰 + 阿本 - 甜甜圈 (官方版MV).mp3"},
{name:"川島茉樹代 KAWASHIMA MAKIYO - 初戀 (官方版MV).mp3",artist:"NA",src:"70_80_typical/川島茉樹代 KAWASHIMA MAKIYO - 初戀 (官方版MV).mp3"},
{name:"川島茉樹代 KAWASHIMA MAKIYO - 養我一輩子 (官方版MV).mp3",artist:"NA",src:"70_80_typical/川島茉樹代 KAWASHIMA MAKIYO - 養我一輩子 (官方版MV).mp3"},
{name:"不公平 Jenny Yang 鬥魚.mp3",artist:"NA",src:"70_80_typical/不公平 Jenny Yang 鬥魚.mp3"},
{name:"不得不? - Wilber Pan and Xianzi Zhang.mp3",artist:"NA",src:"70_80_typical/不得不? - Wilber Pan and Xianzi Zhang.mp3"},
{name:"不愛你 阿爆&Brandy.mp3",artist:"NA",src:"70_80_typical/不愛你 阿爆&Brandy.mp3"},
{name:"中?娃娃-?眼皮女生.mp3",artist:"NA",src:"70_80_typical/中?娃娃-?眼皮女生.mp3"},
{name:"五月天 - 離開地球表面 - KTV.mp3",artist:"NA",src:"70_80_typical/五月天 - 離開地球表面 - KTV.mp3"},
{name:"五月天 Mayday【志明與春嬌 Peter&Mary】Official Music Video.mp3",artist:"NA",src:"70_80_typical/五月天 Mayday【志明與春嬌 Peter&Mary】Official Music Video.mp3"},
{name:"五月天 Mayday【垃圾車 Garbage Truck】Official Music Video.mp3",artist:"NA",src:"70_80_typical/五月天 Mayday【垃圾車 Garbage Truck】Official Music Video.mp3"},
{name:"五月天 Mayday【知足 Contentment】Official Music Video.mp3",artist:"NA",src:"70_80_typical/五月天 Mayday【知足 Contentment】Official Music Video.mp3"},
{name:"五月天 Mayday【終結孤單 Loneliness Terminator】Official Music Video.mp3",artist:"NA",src:"70_80_typical/五月天 Mayday【終結孤單 Loneliness Terminator】Official Music Video.mp3"},
{name:"五月天 Mayday【溫柔 Tenderness】Official Music Video.mp3",artist:"NA",src:"70_80_typical/五月天 Mayday【溫柔 Tenderness】Official Music Video.mp3"},
{name:"五月天 Mayday【戀愛ING Love-ing】Official Music Video.mp3",artist:"NA",src:"70_80_typical/五月天 Mayday【戀愛ING Love-ing】Official Music Video.mp3"},
{name:"元若藍 Shorty Yuan & 吳忠明(大Q) Dr.Q【心願便利貼】台視、三立偶像劇「命中注定我愛你」片尾曲 Official Music Video.mp3",artist:"NA",src:"70_80_typical/元若藍 Shorty Yuan & 吳忠明(大Q) Dr.Q【心願便利貼】台視、三立偶像劇「命中注定我愛你」片尾曲 Official Music Video.mp3"},
{name:"元若藍 Shorty Yuan【99次我愛他 99Times I Love You】台視、三立偶像劇「命中注定我愛你」片頭曲 Official Music Video.mp3",artist:"NA",src:"70_80_typical/元若藍 Shorty Yuan【99次我愛他 99Times I Love You】台視、三立偶像劇「命中注定我愛你」片頭曲 Official Music Video.mp3"},
{name:"元衛覺醒 Awaking《夏天的風 Summer Wind》.mp3",artist:"NA",src:"70_80_typical/元衛覺醒 Awaking《夏天的風 Summer Wind》.mp3"},
{name:"元衛覺醒-夏天的風KTV.mp3",artist:"NA",src:"70_80_typical/元衛覺醒-夏天的風KTV.mp3"},
{name:"方炯鑌 壞人 MV 完整版 HQ.mp3",artist:"NA",src:"70_80_typical/方炯鑌 壞人 MV 完整版 HQ.mp3"},
{name:"王力宏 - kiss goodbye (??歌?).mp3",artist:"NA",src:"70_80_typical/王力宏 - kiss goodbye (??歌?).mp3"},
{name:"王力宏 Leehom Wang - Forever Love.mp3",artist:"NA",src:"70_80_typical/王力宏 Leehom Wang - Forever Love.mp3"},
{name:"王力宏 Leehom Wang - 一首簡單的歌.mp3",artist:"NA",src:"70_80_typical/王力宏 Leehom Wang - 一首簡單的歌.mp3"},
{name:"王力宏 Leehom Wang - 唯一.mp3",artist:"NA",src:"70_80_typical/王力宏 Leehom Wang - 唯一.mp3"},
{name:"王力宏 大城小愛 (Official Video Karaoke).mp3",artist:"NA",src:"70_80_typical/王力宏 大城小愛 (Official Video Karaoke).mp3"},
{name:"王心凌 - Honey.mp3",artist:"NA",src:"70_80_typical/王心凌 - Honey.mp3"},
{name:"王心凌 Cyndi Wang -  彩虹的微笑 (官方完整版MV).mp3",artist:"NA",src:"70_80_typical/王心凌 Cyndi Wang -  彩虹的微笑 (官方完整版MV).mp3"},
{name:"王心凌 我會好好的.mp3",artist:"NA",src:"70_80_typical/王心凌 我會好好的.mp3"},
{name:"王心凌-?的天?.mp3",artist:"NA",src:"70_80_typical/王心凌-?的天?.mp3"},
{name:"王心凌-愛你(月光).mp3",artist:"NA",src:"70_80_typical/王心凌-愛你(月光).mp3"},
{name:"王心凌-當你 (Full HD).mp3",artist:"NA",src:"70_80_typical/王心凌-當你 (Full HD).mp3"},
{name:"王菲 - 流年.mp3",artist:"NA",src:"70_80_typical/王菲 - 流年.mp3"},
{name:"王菲 - 紅豆.mp3",artist:"NA",src:"70_80_typical/王菲 - 紅豆.mp3"},
{name:"王藍茵-惡作劇 (HD).mp3",artist:"NA",src:"70_80_typical/王藍茵-惡作劇 (HD).mp3"},
{name:"可米小子 Comic Boyz - 求愛復刻版.mp3",artist:"NA",src:"70_80_typical/可米小子 Comic Boyz - 求愛復刻版.mp3"},
{name:"可米小子 Comic Boyz - 青春紀念冊.mp3",artist:"NA",src:"70_80_typical/可米小子 Comic Boyz - 青春紀念冊.mp3"},
{name:"永邦 Shaun - 每次都想呼喊妳的名字.mp3",artist:"NA",src:"70_80_typical/永邦 Shaun - 每次都想呼喊妳的名字.mp3"},
{name:"白吉勝《原來愛》（偶像劇【戀香Scent of Love】片尾曲 彭于晏、秋瓷炫 主演）官方MV (Official Music Video).mp3",artist:"NA",src:"70_80_typical/白吉勝《原來愛》（偶像劇【戀香Scent of Love】片尾曲 彭于晏、秋瓷炫 主演）官方MV (Official Music Video).mp3"},
{name:"任賢齊 Richie Jen & 阿牛(陳慶祥) Aniu & 光良 Michael Wong【浪花一朵朵】電影「夏日的麼麼茶」主題曲 Official Music Video.mp3",artist:"NA",src:"70_80_typical/任賢齊 Richie Jen & 阿牛(陳慶祥) Aniu & 光良 Michael Wong【浪花一朵朵】電影「夏日的麼麼茶」主題曲 Official Music Video.mp3"},
{name:"任賢齊 Richie Jen 【傷心太平洋 The Sad Pacific】1998台視「神鵰俠侶」片尾曲 Official Music Video.mp3",artist:"NA",src:"70_80_typical/任賢齊 Richie Jen 【傷心太平洋 The Sad Pacific】1998台視「神鵰俠侶」片尾曲 Official Music Video.mp3"},
{name:"任賢齊 Richie Jen&阿牛(陳慶祥) Aniu (Tan Kheng Seong)【再出發 Set out again】Official Music Video.mp3",artist:"NA",src:"70_80_typical/任賢齊 Richie Jen&阿牛(陳慶祥) Aniu (Tan Kheng Seong)【再出發 Set out again】Official Music Video.mp3"},
{name:"任賢齊 Richie Jen【心太軟 Too softhearted】Official Music Video.mp3",artist:"NA",src:"70_80_typical/任賢齊 Richie Jen【心太軟 Too softhearted】Official Music Video.mp3"},
{name:"任賢齊 Richie Jen【對面的女孩看過來 Look over here, girl】Official Music Video.mp3",artist:"NA",src:"70_80_typical/任賢齊 Richie Jen【對面的女孩看過來 Look over here, girl】Official Music Video.mp3"},
{name:"任賢齊 指揮家.mp3",artist:"NA",src:"70_80_typical/任賢齊 指揮家.mp3"},
{name:"任賢齊 傷心太平洋 (pinyin).mp3",artist:"NA",src:"70_80_typical/任賢齊 傷心太平洋 (pinyin).mp3"},
{name:"伊能靜-一千遍我愛你.mp3",artist:"NA",src:"70_80_typical/伊能靜-一千遍我愛你.mp3"},
{name:"伍佰 Wu Bai&China Blue【挪威的森林 Norwegian forest】Official Music Video.mp3",artist:"NA",src:"70_80_typical/伍佰 Wu Bai&China Blue【挪威的森林 Norwegian forest】Official Music Video.mp3"},
{name:"光良 - 童話【歌詞】.mp3",artist:"NA",src:"70_80_typical/光良 - 童話【歌詞】.mp3"},
{name:"光良 Michael Wong&曹格 Gary Chaw【少年】Official Music Video.mp3",artist:"NA",src:"70_80_typical/光良 Michael Wong&曹格 Gary Chaw【少年】Official Music Video.mp3"},
{name:"光良 Michael Wong【天堂】Official Music Video.mp3",artist:"NA",src:"70_80_typical/光良 Michael Wong【天堂】Official Music Video.mp3"},
{name:"光良 Michael Wong【第一次 First time】Official Music Video.mp3",artist:"NA",src:"70_80_typical/光良 Michael Wong【第一次 First time】Official Music Video.mp3"},
{name:"光良 Michael Wong【童話】Official Music Video.mp3",artist:"NA",src:"70_80_typical/光良 Michael Wong【童話】Official Music Video.mp3"},
{name:"?力火? - ? MV (動力火車-當-還珠格格主題曲).mp3",artist:"NA",src:"70_80_typical/?力火? - ? MV (動力火車-當-還珠格格主題曲).mp3"},
{name:"同恩-失去  官方MV.mp3",artist:"NA",src:"70_80_typical/同恩-失去  官方MV.mp3"},
{name:"江美琪 Maggie Chiang -  我多麼羨慕你 How I Envy You (官方完整版MV).mp3",artist:"NA",src:"70_80_typical/江美琪 Maggie Chiang -  我多麼羨慕你 How I Envy You (官方完整版MV).mp3"},
{name:"江美琪 Maggie Chiang - 親愛的你怎麼不在身邊 Why Aren't You With Me, My Love (官方完整版MV).mp3",artist:"NA",src:"70_80_typical/江美琪 Maggie Chiang - 親愛的你怎麼不在身邊 Why Aren't You With Me, My Love (官方完整版MV).mp3"},
{name:"江得勝-藍夜.mp3",artist:"NA",src:"70_80_typical/江得勝-藍夜.mp3"},
{name:"老鼠愛大米. Mouse Loves Rice.mp3",artist:"NA",src:"70_80_typical/老鼠愛大米. Mouse Loves Rice.mp3"},
{name:"西街少年電視原聲帶-傳說.mp3",artist:"NA",src:"70_80_typical/西街少年電視原聲帶-傳說.mp3"},
{name:"何耀珊 你的肩膀.mp3",artist:"NA",src:"70_80_typical/何耀珊 你的肩膀.mp3"},
{name:"吳克群 - 為你寫詩 KTV.mp3",artist:"NA",src:"70_80_typical/吳克群 - 為你寫詩 KTV.mp3"},
{name:"吳宗憲 -  三暝三日(320K高音質版).mp3",artist:"NA",src:"70_80_typical/吳宗憲 -  三暝三日(320K高音質版).mp3"},
{name:"巫?? - 太傻.mp3",artist:"NA",src:"70_80_typical/巫?? - 太傻.mp3"},
{name:"??建 [一?子一??] 高清.mp3",artist:"NA",src:"70_80_typical/??建 [一?子一??] 高清.mp3"},
{name:"??健_?德?_高高在下（??版）高清MV.mp3",artist:"NA",src:"70_80_typical/??健_?德?_高高在下（??版）高清MV.mp3"},
{name:"忘了?(TORO)-MV.mp3",artist:"NA",src:"70_80_typical/忘了?(TORO)-MV.mp3"},
{name:"李心潔 Sinje Lee【又下雨了 It’s raining again】Official Music Video.mp3",artist:"NA",src:"70_80_typical/李心潔 Sinje Lee【又下雨了 It’s raining again】Official Music Video.mp3"},
{name:"李心潔 Sinje Lee【自由 Free】Official Music Video.mp3",artist:"NA",src:"70_80_typical/李心潔 Sinje Lee【自由 Free】Official Music Video.mp3"},
{name:"李玟 CoCo Lee - Di Da Di.mp3",artist:"NA",src:"70_80_typical/李玟 CoCo Lee - Di Da Di.mp3"},
{name:"李玟 CoCo Lee - 刀馬旦.mp3",artist:"NA",src:"70_80_typical/李玟 CoCo Lee - 刀馬旦.mp3"},
{name:"李玟 CoCo Lee - 好心情.mp3",artist:"NA",src:"70_80_typical/李玟 CoCo Lee - 好心情.mp3"},
{name:"李玟 CoCo Lee - 真情人.mp3",artist:"NA",src:"70_80_typical/李玟 CoCo Lee - 真情人.mp3"},
{name:"李崗霖 - 祈禱.mp3",artist:"NA",src:"70_80_typical/李崗霖 - 祈禱.mp3"},
{name:"李雅微-我們的紀念.mp3",artist:"NA",src:"70_80_typical/李雅微-我們的紀念.mp3"},
{name:"李聖傑 Sam Lee【手放開】Official Music Video.mp3",artist:"NA",src:"70_80_typical/李聖傑 Sam Lee【手放開】Official Music Video.mp3"},
{name:"李聖傑 Sam Lee【最近】Official Music Video.mp3",artist:"NA",src:"70_80_typical/李聖傑 Sam Lee【最近】Official Music Video.mp3"},
{name:"李聖傑 痴心絕對.mp3",artist:"NA",src:"70_80_typical/李聖傑 痴心絕對.mp3"},
{name:"李聖傑-手放開.mp3",artist:"NA",src:"70_80_typical/李聖傑-手放開.mp3"},
{name:"杜德偉 Alex To【脫掉】Official Music Video.mp3",artist:"NA",src:"70_80_typical/杜德偉 Alex To【脫掉】Official Music Video.mp3"},
{name:"杜德偉 Alex To【黑色契約】衛視中文台「第8號當鋪」片頭曲 Official Music Video.mp3",artist:"NA",src:"70_80_typical/杜德偉 Alex To【黑色契約】衛視中文台「第8號當鋪」片頭曲 Official Music Video.mp3"},
{name:"汪佩蓉 Fengie Wang【只要你快樂】Official Music Video.mp3",artist:"NA",src:"70_80_typical/汪佩蓉 Fengie Wang【只要你快樂】Official Music Video.mp3"},
{name:"辛曉琪 Winnie Hsin【味道 Scent】Official Music Video.mp3",artist:"NA",src:"70_80_typical/辛曉琪 Winnie Hsin【味道 Scent】Official Music Video.mp3"},
{name:"辛曉琪 Winnie Hsin【領悟 Understanding】Official Music Video.mp3",artist:"NA",src:"70_80_typical/辛曉琪 Winnie Hsin【領悟 Understanding】Official Music Video.mp3"},
{name:"卓文萱 Genie Chuo&曹格 Gary Chaw【梁山伯與茱麗葉】華視偶像劇「戀愛女王」片尾曲 Official Music Video.mp3",artist:"NA",src:"70_80_typical/卓文萱 Genie Chuo&曹格 Gary Chaw【梁山伯與茱麗葉】華視偶像劇「戀愛女王」片尾曲 Official Music Video.mp3"},
{name:"卓文萱 Genie Chuo&黃鴻升 Alien Huang【愛的主旋律】Official Music Video.mp3",artist:"NA",src:"70_80_typical/卓文萱 Genie Chuo&黃鴻升 Alien Huang【愛的主旋律】Official Music Video.mp3"},
{name:"卓文萱 Genie Chuo【不要不要】台視、三立華劇「小資女孩向前衝」片頭曲 Official Music Video.mp3",artist:"NA",src:"70_80_typical/卓文萱 Genie Chuo【不要不要】台視、三立華劇「小資女孩向前衝」片頭曲 Official Music Video.mp3"},
{name:"卓文萱 Genie Chuo【想飛的自由落體】台視、三立華劇「小資女孩向前衝」插曲 Official Music Video.mp3",artist:"NA",src:"70_80_typical/卓文萱 Genie Chuo【想飛的自由落體】台視、三立華劇「小資女孩向前衝」插曲 Official Music Video.mp3"},
{name:"周杰倫 Jay Chou【上海 一九四三 Shanghai 1943】Official MV.mp3",artist:"NA",src:"70_80_typical/周杰倫 Jay Chou【上海 一九四三 Shanghai 1943】Official MV.mp3"},
{name:"周杰倫 Jay Chou【以父之名 In The Name of The Father】Official MV.mp3",artist:"NA",src:"70_80_typical/周杰倫 Jay Chou【以父之名 In The Name of The Father】Official MV.mp3"},
{name:"周杰倫 Jay Chou【半島鐵盒 Peninsula Ironbox】Official MV.mp3",artist:"NA",src:"70_80_typical/周杰倫 Jay Chou【半島鐵盒 Peninsula Ironbox】Official MV.mp3"},
{name:"周杰倫 Jay Chou【半獸人 Half-beast Human】Official MV.mp3",artist:"NA",src:"70_80_typical/周杰倫 Jay Chou【半獸人 Half-beast Human】Official MV.mp3"},
{name:"周杰倫 Jay Chou【夜曲 Nocturne】Official Music Video.mp3",artist:"NA",src:"70_80_typical/周杰倫 Jay Chou【夜曲 Nocturne】Official Music Video.mp3"},
{name:"周杰倫 Jay Chou【開不了口 I Find It Hard To Say】Official MV.mp3",artist:"NA",src:"70_80_typical/周杰倫 Jay Chou【開不了口 I Find It Hard To Say】Official MV.mp3"},
{name:"周杰倫 Jay Chou【愛在西元前 Love before BC】Official MV.mp3",artist:"NA",src:"70_80_typical/周杰倫 Jay Chou【愛在西元前 Love before BC】Official MV.mp3"},
{name:"周杰倫 Jay Chou【爺爺泡的茶 Grandpa's Tea】Official MV.mp3",artist:"NA",src:"70_80_typical/周杰倫 Jay Chou【爺爺泡的茶 Grandpa's Tea】Official MV.mp3"},
{name:"周杰倫 Jay Chou【簡單愛 Simple Love】Official MV.mp3",artist:"NA",src:"70_80_typical/周杰倫 Jay Chou【簡單愛 Simple Love】Official MV.mp3"},
{name:"周杰倫 Jay Chou【雙截棍 Nunchucks】Official MV.mp3",artist:"NA",src:"70_80_typical/周杰倫 Jay Chou【雙截棍 Nunchucks】Official MV.mp3"},
{name:"周杰倫 Jay Chou【飄移 Drifting】(頭文字D???版)-Official Music Video.mp3",artist:"NA",src:"70_80_typical/周杰倫 Jay Chou【飄移 Drifting】(頭文字D???版)-Official Music Video.mp3"},
{name:"周杰倫 溫嵐-屋頂.mp3",artist:"NA",src:"70_80_typical/周杰倫 溫嵐-屋頂.mp3"},
{name:"周杰倫 蒲公英的?定 MV 高畫值.mp3",artist:"NA",src:"70_80_typical/周杰倫 蒲公英的?定 MV 高畫值.mp3"},
{name:"周杰倫&Lara - 珊瑚海 HD.mp3",artist:"NA",src:"70_80_typical/周杰倫&Lara - 珊瑚海 HD.mp3"},
{name:"周杰倫【可愛女人 官方完整MV】Jay Chou Adorable Lady MV (feat.徐若瑄Vivian) (Ke-Ai-Nu-Ren).mp3",artist:"NA",src:"70_80_typical/周杰倫【可愛女人 官方完整MV】Jay Chou Adorable Lady MV (feat.徐若瑄Vivian) (Ke-Ai-Nu-Ren).mp3"},
{name:"周杰倫【龍捲風 官方完整MV】Jay Chou Tornado MV (Long-Juan-Feng).mp3",artist:"NA",src:"70_80_typical/周杰倫【龍捲風 官方完整MV】Jay Chou Tornado MV (Long-Juan-Feng).mp3"},
{name:"周杰倫【擱淺 官方完整MV】Jay Chou Step Aside MV (Ge-Qian).mp3",artist:"NA",src:"70_80_typical/周杰倫【擱淺 官方完整MV】Jay Chou Step Aside MV (Ge-Qian).mp3"},
{name:"周華健 Wakin Chau 【有沒有一首歌會讓你想起我 Any song reminds you or me 】中視「青蛇與白蛇」片尾曲 Official Music Video.mp3",artist:"NA",src:"70_80_typical/周華健 Wakin Chau 【有沒有一首歌會讓你想起我 Any song reminds you or me 】中視「青蛇與白蛇」片尾曲 Official Music Video.mp3"},
{name:"周華健 Wakin Chau【朋友 Friends】Official Music Video.mp3",artist:"NA",src:"70_80_typical/周華健 Wakin Chau【朋友 Friends】Official Music Video.mp3"},
{name:"周華健 Wakin Chau【花心 The flowery heart】Official Music Video.mp3",artist:"NA",src:"70_80_typical/周華健 Wakin Chau【花心 The flowery heart】Official Music Video.mp3"},
{name:"周傳雄-黃昏.wmv.mp3",artist:"NA",src:"70_80_typical/周傳雄-黃昏.wmv.mp3"},
{name:"周蕙 Where Chou - 不想讓你知道 (官方版MV).mp3",artist:"NA",src:"70_80_typical/周蕙 Where Chou - 不想讓你知道 (官方版MV).mp3"},
{name:"周蕙 Where Chou - 好想好好愛你 (官方版MV).mp3",artist:"NA",src:"70_80_typical/周蕙 Where Chou - 好想好好愛你 (官方版MV).mp3"},
{name:"周蕙 Where Chou - 約定 (官方版MV).mp3",artist:"NA",src:"70_80_typical/周蕙 Where Chou - 約定 (官方版MV).mp3"},
{name:"放手-Energy MV.mp3",artist:"NA",src:"70_80_typical/放手-Energy MV.mp3"},
{name:"林志炫 Terry Lin - 單身情歌.mp3",artist:"NA",src:"70_80_typical/林志炫 Terry Lin - 單身情歌.mp3"},
{name:"林依晨 Ariel Lin【孤單北半球】TVBS-G偶像劇「愛情合約」片尾曲 Official Music Video.mp3",artist:"NA",src:"70_80_typical/林依晨 Ariel Lin【孤單北半球】TVBS-G偶像劇「愛情合約」片尾曲 Official Music Video.mp3"},
{name:"林俊傑  愛笑的眼睛 完整版MV.mp3",artist:"NA",src:"70_80_typical/林俊傑  愛笑的眼睛 完整版MV.mp3"},
{name:"林俊傑 JJ Lin【一千年以後 A Thousand Years Later】官方完整版 MV.mp3",artist:"NA",src:"70_80_typical/林俊傑 JJ Lin【一千年以後 A Thousand Years Later】官方完整版 MV.mp3"},
{name:"林俊傑 JJ Lin【小酒窩 Dimples】（合唱：蔡卓妍 A-Sa）官方完整版 MV.mp3",artist:"NA",src:"70_80_typical/林俊傑 JJ Lin【小酒窩 Dimples】（合唱：蔡卓妍 A-Sa）官方完整版 MV.mp3"},
{name:"林俊傑 JJ Lin【只對你說  Sarang Heyo ????】官方完整版 MV.mp3",artist:"NA",src:"70_80_typical/林俊傑 JJ Lin【只對你說  Sarang Heyo ????】官方完整版 MV.mp3"},
{name:"林俊傑 JJ Lin【江南 River South】官方完整版 MV.mp3",artist:"NA",src:"70_80_typical/林俊傑 JJ Lin【江南 River South】官方完整版 MV.mp3"},
{name:"林俊傑 JJ Lin【豆漿油條 Perfect Match】官方完整版 MV.mp3",artist:"NA",src:"70_80_typical/林俊傑 JJ Lin【豆漿油條 Perfect Match】官方完整版 MV.mp3"},
{name:"林俊傑 JJ Lin【背對背擁抱 Back To Back】官方完整版 MV.mp3",artist:"NA",src:"70_80_typical/林俊傑 JJ Lin【背對背擁抱 Back To Back】官方完整版 MV.mp3"},
{name:"林俊傑 JJ Lin【凍結 Freeze】官方完整版 MV.mp3",artist:"NA",src:"70_80_typical/林俊傑 JJ Lin【凍結 Freeze】官方完整版 MV.mp3"},
{name:"林俊傑 JJ Lin【曹操 CaoCao】官方完整版 MV.mp3",artist:"NA",src:"70_80_typical/林俊傑 JJ Lin【曹操 CaoCao】官方完整版 MV.mp3"},
{name:"林俊傑 JJ Lin【被風吹過的夏天】（合唱：金莎）官方完整版 MV.mp3",artist:"NA",src:"70_80_typical/林俊傑 JJ Lin【被風吹過的夏天】（合唱：金莎）官方完整版 MV.mp3"},
{name:"林俊傑 JJ Lin【簡簡單單 Simply】官方完整版 MV.mp3",artist:"NA",src:"70_80_typical/林俊傑 JJ Lin【簡簡單單 Simply】官方完整版 MV.mp3"},
{name:"林冠吟-梁祝.mp3",artist:"NA",src:"70_80_typical/林冠吟-梁祝.mp3"},
{name:"林冠吟-毀滅愛情(2004).mp3",artist:"NA",src:"70_80_typical/林冠吟-毀滅愛情(2004).mp3"},
{name:"林隆璇 Kevin Lin - 你那麼愛她 (官方版MV) - 電視劇《前男友不是人》插曲.mp3",artist:"NA",src:"70_80_typical/林隆璇 Kevin Lin - 你那麼愛她 (官方版MV) - 電視劇《前男友不是人》插曲.mp3"},
{name:"林憶蓮 Sandy Lam - 至少還有你 At Least I've Got You (官方完整版MV).mp3",artist:"NA",src:"70_80_typical/林憶蓮 Sandy Lam - 至少還有你 At Least I've Got You (官方完整版MV).mp3"},
{name:"林曉培 - 心動.mp3",artist:"NA",src:"70_80_typical/林曉培 - 心動.mp3"},
{name:"林曉培 - 她的眼淚 MV.mp3",artist:"NA",src:"70_80_typical/林曉培 - 她的眼淚 MV.mp3"},
{name:"林曉培 心動.mp3",artist:"NA",src:"70_80_typical/林曉培 心動.mp3"},
{name:"沿海地帶.mp3",artist:"NA",src:"70_80_typical/沿海地帶.mp3"},
{name:"芮恩 - 討厭.mp3",artist:"NA",src:"70_80_typical/芮恩 - 討厭.mp3"},
{name:"阿杜 A-Do【他一定很愛你 He Loves You Very Much】官方完整版 MV.mp3",artist:"NA",src:"70_80_typical/阿杜 A-Do【他一定很愛你 He Loves You Very Much】官方完整版 MV.mp3"},
{name:"阿杜-他一定很愛你.mp3",artist:"NA",src:"70_80_typical/阿杜-他一定很愛你.mp3"},
{name:"阿桑 - 寂寞在唱歌.mp3",artist:"NA",src:"70_80_typical/阿桑 - 寂寞在唱歌.mp3"},
{name:"阿桑 - 葉子(高音質).mp3",artist:"NA",src:"70_80_typical/阿桑 - 葉子(高音質).mp3"},
{name:"阿密特張惠妹 A-MIT - 掉了 Disappear (official官方完整版MV).mp3",artist:"NA",src:"70_80_typical/阿密特張惠妹 A-MIT - 掉了 Disappear (official官方完整版MV).mp3"},
{name:"青花瓷 MV （完整版）.mp3",artist:"NA",src:"70_80_typical/青花瓷 MV （完整版）.mp3"},
{name:"侯湘婷 Angel Hou - 兩個冬天 (官方完整版MV).mp3",artist:"NA",src:"70_80_typical/侯湘婷 Angel Hou - 兩個冬天 (官方完整版MV).mp3"},
{name:"信徒 (張衛健).mp3",artist:"NA",src:"70_80_typical/信徒 (張衛健).mp3"},
{name:"信樂團- 一了百了.mp3",artist:"NA",src:"70_80_typical/信樂團- 一了百了.mp3"},
{name:"南拳媽媽 - 下雨天.mp3",artist:"NA",src:"70_80_typical/南拳媽媽 - 下雨天.mp3"},
{name:"南拳媽媽 - 香草把噗.mp3",artist:"NA",src:"70_80_typical/南拳媽媽 - 香草把噗.mp3"},
{name:"南拳媽媽 -牡丹江 MOU DAN CHIANG(Official Music Video).mp3",artist:"NA",src:"70_80_typical/南拳媽媽 -牡丹江 MOU DAN CHIANG(Official Music Video).mp3"},
{name:"南拳媽媽 -橘子汽水CHU TZU CHI SHUI (Official Music Video).mp3",artist:"NA",src:"70_80_typical/南拳媽媽 -橘子汽水CHU TZU CHI SHUI (Official Music Video).mp3"},
{name:"南拳媽媽(Nan Quan Mama)-下雨天Xia Yu Tian (Official Music Video).mp3",artist:"NA",src:"70_80_typical/南拳媽媽(Nan Quan Mama)-下雨天Xia Yu Tian (Official Music Video).mp3"},
{name:"星光2班 你們是我的星光.mp3",artist:"NA",src:"70_80_typical/星光2班 你們是我的星光.mp3"},
{name:"星光幫 [ 因為我相信 ] Official Music Video.mp3",artist:"NA",src:"70_80_typical/星光幫 [ 因為我相信 ] Official Music Video.mp3"},
{name:"柯有綸 Alan Kuo - 哭笑不得.mp3",artist:"NA",src:"70_80_typical/柯有綸 Alan Kuo - 哭笑不得.mp3"},
{name:"柯有綸 Alan Kuo - 零.mp3",artist:"NA",src:"70_80_typical/柯有綸 Alan Kuo - 零.mp3"},
{name:"胡彥斌 - Waiting for you.mp3",artist:"NA",src:"70_80_typical/胡彥斌 - Waiting for you.mp3"},
{name:"范逸臣 Van Fan《I BELIEVE》（電影【我的野蠻女友】中文主題曲 車太鉉、全智賢 主演）官方MV (Official Music Video).mp3",artist:"NA",src:"70_80_typical/范逸臣 Van Fan《I BELIEVE》（電影【我的野蠻女友】中文主題曲 車太鉉、全智賢 主演）官方MV (Official Music Video).mp3"},
{name:"范逸臣 Van Fan《Love Story》官方MV (Official Music Video).mp3",artist:"NA",src:"70_80_typical/范逸臣 Van Fan《Love Story》官方MV (Official Music Video).mp3"},
{name:"范逸臣 Van Fan《放生》官方MV (Official Music Video).mp3",artist:"NA",src:"70_80_typical/范逸臣 Van Fan《放生》官方MV (Official Music Video).mp3"},
{name:"范逸臣 Van Fan《無樂不作》（電影【海角七號 Cape No. 7】主題曲 范逸臣、田中千繪 主演）官方MV (Official Music Video).mp3",artist:"NA",src:"70_80_typical/范逸臣 Van Fan《無樂不作》（電影【海角七號 Cape No. 7】主題曲 范逸臣、田中千繪 主演）官方MV (Official Music Video).mp3"},
{name:"范瑋琪 Christine Fan - 一個像夏天 一個像秋天 (官方版MV).mp3",artist:"NA",src:"70_80_typical/范瑋琪 Christine Fan - 一個像夏天 一個像秋天 (官方版MV).mp3"},
{name:"范瑋琪 Christine Fan - 可不可以不勇敢 (官方版MV).mp3",artist:"NA",src:"70_80_typical/范瑋琪 Christine Fan - 可不可以不勇敢 (官方版MV).mp3"},
{name:"范瑋琪 Christine Fan - 如果的事 (官方版MV).mp3",artist:"NA",src:"70_80_typical/范瑋琪 Christine Fan - 如果的事 (官方版MV).mp3"},
{name:"范瑋琪 Christine Fan - 到不了 (官方版MV).mp3",artist:"NA",src:"70_80_typical/范瑋琪 Christine Fan - 到不了 (官方版MV).mp3"},
{name:"范瑋琪 Christine Fan - 啟程 (官方版MV).mp3",artist:"NA",src:"70_80_typical/范瑋琪 Christine Fan - 啟程 (官方版MV).mp3"},
{name:"范曉萱 Mavis Fan - 你的甜蜜 (官方版MV).mp3",artist:"NA",src:"70_80_typical/范曉萱 Mavis Fan - 你的甜蜜 (官方版MV).mp3"},
{name:"范曉萱 Mavis Fan - 氧氣 (官方版MV).mp3",artist:"NA",src:"70_80_typical/范曉萱 Mavis Fan - 氧氣 (官方版MV).mp3"},
{name:"范曉萱 Mavis Fan - 健康歌 (官方版MV).mp3",artist:"NA",src:"70_80_typical/范曉萱 Mavis Fan - 健康歌 (官方版MV).mp3"},
{name:"郁可唯《好朋友只是朋友》.mp3",artist:"NA",src:"70_80_typical/郁可唯《好朋友只是朋友》.mp3"},
{name:"韋禮安 Weibird Wei - 有沒有 (官方版MV).mp3",artist:"NA",src:"70_80_typical/韋禮安 Weibird Wei - 有沒有 (官方版MV).mp3"},
{name:"韋禮安-還是會(我可能不會愛你OST)-官方完整版MV.mp3",artist:"NA",src:"70_80_typical/韋禮安-還是會(我可能不會愛你OST)-官方完整版MV.mp3"},
{name:"飛輪海 Fahrenheit feat. Hebe [只對你有感覺 Only have feelings for you] Official MV.mp3",artist:"NA",src:"70_80_typical/飛輪海 Fahrenheit feat. Hebe [只對你有感覺 Only have feelings for you] Official MV.mp3"},
{name:"倪安東 Anthony Neely [Sorry That I Loved You] Official MV.mp3",artist:"NA",src:"70_80_typical/倪安東 Anthony Neely [Sorry That I Loved You] Official MV.mp3"},
{name:"倪安東 Anthony Neely [散場的擁抱 The Last Embrace] Official MV.mp3",artist:"NA",src:"70_80_typical/倪安東 Anthony Neely [散場的擁抱 The Last Embrace] Official MV.mp3"},
{name:"孫協志.王心凌 - 煎熬 (224kpbs版).mp3",artist:"NA",src:"70_80_typical/孫協志.王心凌 - 煎熬 (224kpbs版).mp3"},
{name:"孫燕姿 - 超快感.mp3",artist:"NA",src:"70_80_typical/孫燕姿 - 超快感.mp3"},
{name:"孫燕姿 - 綠光.mp3",artist:"NA",src:"70_80_typical/孫燕姿 - 綠光.mp3"},
{name:"孫燕姿 Sun Yan-Zi -  逆光 Against The Light (official 官方完整版MV).mp3",artist:"NA",src:"70_80_typical/孫燕姿 Sun Yan-Zi -  逆光 Against The Light (official 官方完整版MV).mp3"},
{name:"孫燕姿 Sun Yan-Zi - 天黑黑 Cloudy Day (official 官方完整版MV).mp3",artist:"NA",src:"70_80_typical/孫燕姿 Sun Yan-Zi - 天黑黑 Cloudy Day (official 官方完整版MV).mp3"},
{name:"孫燕姿 Sun Yan-Zi - 我也很想他 I Miss Him, Too (official 官方完整版MV).mp3",artist:"NA",src:"70_80_typical/孫燕姿 Sun Yan-Zi - 我也很想他 I Miss Him, Too (official 官方完整版MV).mp3"},
{name:"孫燕姿 Sun Yan-Zi - 我不難過 I Am Fine (official 官方完整版MV).mp3",artist:"NA",src:"70_80_typical/孫燕姿 Sun Yan-Zi - 我不難過 I Am Fine (official 官方完整版MV).mp3"},
{name:"孫燕姿 Sun Yan-Zi - 風箏 Kite (official 官方完整版MV).mp3",artist:"NA",src:"70_80_typical/孫燕姿 Sun Yan-Zi - 風箏 Kite (official 官方完整版MV).mp3"},
{name:"孫燕姿 Sun Yan-Zi - 第一天 First Day (official 官方完整版MV).mp3",artist:"NA",src:"70_80_typical/孫燕姿 Sun Yan-Zi - 第一天 First Day (official 官方完整版MV).mp3"},
{name:"孫燕姿 Sun Yan-Zi - 開始懂了 Realize (official 官方完整版MV).mp3",artist:"NA",src:"70_80_typical/孫燕姿 Sun Yan-Zi - 開始懂了 Realize (official 官方完整版MV).mp3"},
{name:"孫燕姿 Sun Yan-Zi - 遇見 Encounter (official 官方完整版MV).mp3",artist:"NA",src:"70_80_typical/孫燕姿 Sun Yan-Zi - 遇見 Encounter (official 官方完整版MV).mp3"},
{name:"徐佳瑩 LaLa【身騎白馬 】[Official Music Video].mp3",artist:"NA",src:"70_80_typical/徐佳瑩 LaLa【身騎白馬 】[Official Music Video].mp3"},
{name:"徐若瑄-狠狠愛.mp3",artist:"NA",src:"70_80_typical/徐若瑄-狠狠愛.mp3"},
{name:"徐婕兒 - I wanna be with you (官方版MV) - 電視劇《前男友不是人》插曲.mp3",artist:"NA",src:"70_80_typical/徐婕兒 - I wanna be with you (官方版MV) - 電視劇《前男友不是人》插曲.mp3"},
{name:"徐婕兒 - TIC TAC TOE (官方版MV).mp3",artist:"NA",src:"70_80_typical/徐婕兒 - TIC TAC TOE (官方版MV).mp3"},
{name:"徐婕兒 - 沒有你的每一天 (官方版MV).mp3",artist:"NA",src:"70_80_typical/徐婕兒 - 沒有你的每一天 (官方版MV).mp3"},
{name:"徐婕兒 - 錯誤的相遇 (官方版MV).mp3",artist:"NA",src:"70_80_typical/徐婕兒 - 錯誤的相遇 (官方版MV).mp3"},
{name:"徐懷鈺 Yuki&任賢齊 Richie Jen【水晶 Cheot sarang】Official Music Video.mp3",artist:"NA",src:"70_80_typical/徐懷鈺 Yuki&任賢齊 Richie Jen【水晶 Cheot sarang】Official Music Video.mp3"},
{name:"徐懷鈺 Yuki【分飛】Official Music Video.mp3",artist:"NA",src:"70_80_typical/徐懷鈺 Yuki【分飛】Official Music Video.mp3"},
{name:"徐懷鈺 Yuki【妙妙妙 Fantastic】Official Music Video.mp3",artist:"NA",src:"70_80_typical/徐懷鈺 Yuki【妙妙妙 Fantastic】Official Music Video.mp3"},
{name:"徐懷鈺 Yuki【怪獸 The monster】Official Music Video.mp3",artist:"NA",src:"70_80_typical/徐懷鈺 Yuki【怪獸 The monster】Official Music Video.mp3"},
{name:"殷悅-愛多少早知道.mp3",artist:"NA",src:"70_80_typical/殷悅-愛多少早知道.mp3"},
{name:"浪花兄弟 The Drifters【你是我的OK繃 You're My Bandaid】Official MV.mp3",artist:"NA",src:"70_80_typical/浪花兄弟 The Drifters【你是我的OK繃 You're My Bandaid】Official MV.mp3"},
{name:"祝福 – 張學友 (Official MV).mp3",artist:"NA",src:"70_80_typical/祝福 – 張學友 (Official MV).mp3"},
{name:"神木與瞳 - 為你而活 English Subbed.mp3",artist:"NA",src:"70_80_typical/神木與瞳 - 為你而活 English Subbed.mp3"},
{name:"動力火車 Power Station [ 忠孝東路走九遍 ] Official Music Video.mp3",artist:"NA",src:"70_80_typical/動力火車 Power Station [ 忠孝東路走九遍 ] Official Music Video.mp3"},
{name:"動力火車 Power Station [ 彩虹 Rainbow ] Official Music Video.mp3",artist:"NA",src:"70_80_typical/動力火車 Power Station [ 彩虹 Rainbow ] Official Music Video.mp3"},
{name:"動力火車Power Station [ 外套 Coat ] Official Music Video.mp3",artist:"NA",src:"70_80_typical/動力火車Power Station [ 外套 Coat ] Official Music Video.mp3"},
{name:"匿名的寶貝 by 黃義達 Yida Huang.mp3",artist:"NA",src:"70_80_typical/匿名的寶貝 by 黃義達 Yida Huang.mp3"},
{name:"寂寞邊界-張棟樑.mp3",artist:"NA",src:"70_80_typical/寂寞邊界-張棟樑.mp3"},
{name:"庾澄慶 - 情非得已.mp3",artist:"NA",src:"70_80_typical/庾澄慶 - 情非得已.mp3"},
{name:"庾澄慶 Harlem Yu - 春泥.mp3",artist:"NA",src:"70_80_typical/庾澄慶 Harlem Yu - 春泥.mp3"},
{name:"張玉華   原諒.mp3",artist:"NA",src:"70_80_typical/張玉華   原諒.mp3"},
{name:"張宇  傘下.mp3",artist:"NA",src:"70_80_typical/張宇  傘下.mp3"},
{name:"張宇 Phil Chang -  月亮惹的禍 Troubled By The Moon (官方完整版MV).mp3",artist:"NA",src:"70_80_typical/張宇 Phil Chang -  月亮惹的禍 Troubled By The Moon (官方完整版MV).mp3"},
{name:"張宇 Phil Chang -  雨一直下 Rain Keeps Falling (官方完整版MV).mp3",artist:"NA",src:"70_80_typical/張宇 Phil Chang -  雨一直下 Rain Keeps Falling (官方完整版MV).mp3"},
{name:"張雨生《口是心非》官方MV (Official Music Video).mp3",artist:"NA",src:"70_80_typical/張雨生《口是心非》官方MV (Official Music Video).mp3"},
{name:"張善為 SAKURA真夏的櫻花 官方正式版MV.mp3",artist:"NA",src:"70_80_typical/張善為 SAKURA真夏的櫻花 官方正式版MV.mp3"},
{name:"張惠妹 A-Mei - BAD BOY 官方MV (Official Music Video).mp3",artist:"NA",src:"70_80_typical/張惠妹 A-Mei - BAD BOY 官方MV (Official Music Video).mp3"},
{name:"張惠妹 A-Mei - 人質 Hostage (official 官方完整版MV).mp3",artist:"NA",src:"70_80_typical/張惠妹 A-Mei - 人質 Hostage (official 官方完整版MV).mp3"},
{name:"張惠妹 A-Mei - 三天三夜 官方MV (Official Music Video).mp3",artist:"NA",src:"70_80_typical/張惠妹 A-Mei - 三天三夜 官方MV (Official Music Video).mp3"},
{name:"張惠妹 A-Mei - 我要快樂？I Want Happiness (official 官方完整版MV).mp3",artist:"NA",src:"70_80_typical/張惠妹 A-Mei - 我要快樂？I Want Happiness (official 官方完整版MV).mp3"},
{name:"張惠妹 A-Mei - 我最親愛的 My Dearest (official官方完整版MV).mp3",artist:"NA",src:"70_80_typical/張惠妹 A-Mei - 我最親愛的 My Dearest (official官方完整版MV).mp3"},
{name:"張惠妹 A-Mei - 姊妹 官方MV (Official Music Video).mp3",artist:"NA",src:"70_80_typical/張惠妹 A-Mei - 姊妹 官方MV (Official Music Video).mp3"},
{name:"張惠妹 A-Mei - 勇敢 Brave (official 官方完整版MV).mp3",artist:"NA",src:"70_80_typical/張惠妹 A-Mei - 勇敢 Brave (official 官方完整版MV).mp3"},
{name:"張惠妹 A-Mei - 原來你什麼都不要 官方MV (Official Music Video).mp3",artist:"NA",src:"70_80_typical/張惠妹 A-Mei - 原來你什麼都不要 官方MV (Official Music Video).mp3"},
{name:"張惠妹 A-Mei - 站在高崗上  官方MV (Official Music Video).mp3",artist:"NA",src:"70_80_typical/張惠妹 A-Mei - 站在高崗上  官方MV (Official Music Video).mp3"},
{name:"張惠妹 A-Mei - 記得 Remember (official 官方完整版MV).mp3",artist:"NA",src:"70_80_typical/張惠妹 A-Mei - 記得 Remember (official 官方完整版MV).mp3"},
{name:"張惠妹 A-Mei - 剪愛 官方MV (Official Music Video).mp3",artist:"NA",src:"70_80_typical/張惠妹 A-Mei - 剪愛 官方MV (Official Music Video).mp3"},
{name:"張惠妹 A-Mei - 聽海 官方MV (Official Music Video).mp3",artist:"NA",src:"70_80_typical/張惠妹 A-Mei - 聽海 官方MV (Official Music Video).mp3"},
{name:"張智成 Z Chen [ 末日之戀 ] Official Music Video.mp3",artist:"NA",src:"70_80_typical/張智成 Z Chen [ 末日之戀 ] Official Music Video.mp3"},
{name:"張智成 Z-Chen [ May I Love You ] Official Music Video.mp3",artist:"NA",src:"70_80_typical/張智成 Z-Chen [ May I Love You ] Official Music Video.mp3"},
{name:"張智成 Z-Chen [ 凌晨三點鐘 ] Official Music Video.mp3",artist:"NA",src:"70_80_typical/張智成 Z-Chen [ 凌晨三點鐘 ] Official Music Video.mp3"},
{name:"張棟樑 Nicholas Teo - 北極星的眼淚 Tears From Polaris (官方完整KARAOKE版MV).mp3",artist:"NA",src:"70_80_typical/張棟樑 Nicholas Teo - 北極星的眼淚 Tears From Polaris (官方完整KARAOKE版MV).mp3"},
{name:"張棟樑 Nicholas Teo - 當你孤單你會想起誰 Who Will U Think Of (官方完整KARAOKE版MV).mp3",artist:"NA",src:"70_80_typical/張棟樑 Nicholas Teo - 當你孤單你會想起誰 Who Will U Think Of (官方完整KARAOKE版MV).mp3"},
{name:"張韶涵 Angela Zhang - C大調 (官方版MV).mp3",artist:"NA",src:"70_80_typical/張韶涵 Angela Zhang - C大調 (官方版MV).mp3"},
{name:"張韶涵 Angela Zhang - 口袋的天空 (官方版MV).mp3",artist:"NA",src:"70_80_typical/張韶涵 Angela Zhang - 口袋的天空 (官方版MV).mp3"},
{name:"張韶涵 Angela Zhang - 不想懂得 (官方版MV).mp3",artist:"NA",src:"70_80_typical/張韶涵 Angela Zhang - 不想懂得 (官方版MV).mp3"},
{name:"張韶涵 Angela Zhang - 寓言 (官方版MV).mp3",artist:"NA",src:"70_80_typical/張韶涵 Angela Zhang - 寓言 (官方版MV).mp3"},
{name:"張韶涵 Angela Zhang - 歐若拉 (官方版MV).mp3",artist:"NA",src:"70_80_typical/張韶涵 Angela Zhang - 歐若拉 (官方版MV).mp3"},
{name:"張韶涵 Angela Zhang - 遺失的美好 (官方版MV).mp3",artist:"NA",src:"70_80_typical/張韶涵 Angela Zhang - 遺失的美好 (官方版MV).mp3"},
{name:"張韶涵 Angela Zhang - 頭號甜心 (官方版MV).mp3",artist:"NA",src:"70_80_typical/張韶涵 Angela Zhang - 頭號甜心 (官方版MV).mp3"},
{name:"張韶涵 Angela Zhang - 隱形的翅膀 (官方版MV).mp3",artist:"NA",src:"70_80_typical/張韶涵 Angela Zhang - 隱形的翅膀 (官方版MV).mp3"},
{name:"張衛健 - 你愛我像誰.mp3",artist:"NA",src:"70_80_typical/張衛健 - 你愛我像誰.mp3"},
{name:"張震嶽 A-Yue & 林芯儀 Shennio Lin【回到過去】中視「光陰的故事」片尾曲 Official Music Video.mp3",artist:"NA",src:"70_80_typical/張震嶽 A-Yue & 林芯儀 Shennio Lin【回到過去】中視「光陰的故事」片尾曲 Official Music Video.mp3"},
{name:"張震嶽 A-Yue【自由 Free】Official Music Video.mp3",artist:"NA",src:"70_80_typical/張震嶽 A-Yue【自由 Free】Official Music Video.mp3"},
{name:"張震嶽 A-Yue【思念是一種病】Official Music Video.mp3",artist:"NA",src:"70_80_typical/張震嶽 A-Yue【思念是一種病】Official Music Video.mp3"},
{name:"張震嶽 A-Yue【乾妹妹 Little sister】Official Music Video.mp3",artist:"NA",src:"70_80_typical/張震嶽 A-Yue【乾妹妹 Little sister】Official Music Video.mp3"},
{name:"張震嶽 A-Yue【愛我別走 Love me,don’t go】Official Music Video.mp3",artist:"NA",src:"70_80_typical/張震嶽 A-Yue【愛我別走 Love me,don’t go】Official Music Video.mp3"},
{name:"張震嶽 A-Yue【愛的初體驗 Love's first taste】Official Music Video.mp3",artist:"NA",src:"70_80_typical/張震嶽 A-Yue【愛的初體驗 Love's first taste】Official Music Video.mp3"},
{name:"曹格 Gary Chaw【世界唯一的你】Official Music Video.mp3",artist:"NA",src:"70_80_typical/曹格 Gary Chaw【世界唯一的你】Official Music Video.mp3"},
{name:"曹格 Gary Chaw【背叛】Official Music Video.mp3",artist:"NA",src:"70_80_typical/曹格 Gary Chaw【背叛】Official Music Video.mp3"},
{name:"梁?琪 - ?小鬼 MV.mp3",artist:"NA",src:"70_80_typical/梁?琪 - ?小鬼 MV.mp3"},
{name:"梁詠琪 - 偏見 [Album Rip].mp3",artist:"NA",src:"70_80_typical/梁詠琪 - 偏見 [Album Rip].mp3"},
{name:"梁靜茹 - 愛情之所以為愛情【歌詞】.mp3",artist:"NA",src:"70_80_typical/梁靜茹 - 愛情之所以為愛情【歌詞】.mp3"},
{name:"梁靜茹 Fish Leong【Fly away】Official Music Video.mp3",artist:"NA",src:"70_80_typical/梁靜茹 Fish Leong【Fly away】Official Music Video.mp3"},
{name:"梁靜茹 Fish Leong【中間 In The Middle】TVBS-G偶像劇「愛情合約」片頭曲 Official Music Video.mp3",artist:"NA",src:"70_80_typical/梁靜茹 Fish Leong【中間 In The Middle】TVBS-G偶像劇「愛情合約」片頭曲 Official Music Video.mp3"},
{name:"梁靜茹 Fish Leong【分手快樂(獨唱版) Break Up Happily (Solo Version)】台視「吐司男之吻2─愛情本事」片尾曲 Official Music Video.mp3",artist:"NA",src:"70_80_typical/梁靜茹 Fish Leong【分手快樂(獨唱版) Break Up Happily (Solo Version)】台視「吐司男之吻2─愛情本事」片尾曲 Official Music Video.mp3"},
{name:"梁靜茹 Fish Leong【可惜不是你 Unfortunately Not You】Official Music Video.mp3",artist:"NA",src:"70_80_typical/梁靜茹 Fish Leong【可惜不是你 Unfortunately Not You】Official Music Video.mp3"},
{name:"梁靜茹 Fish Leong【如果有一天 If One Day】GTV28台「懷玉公主」片頭曲 Official Music Video.mp3",artist:"NA",src:"70_80_typical/梁靜茹 Fish Leong【如果有一天 If One Day】GTV28台「懷玉公主」片頭曲 Official Music Video.mp3"},
{name:"梁靜茹 Fish Leong【勇氣 Courage】台視「俠女闖天關」主題曲 Official Music Video.mp3",artist:"NA",src:"70_80_typical/梁靜茹 Fish Leong【勇氣 Courage】台視「俠女闖天關」主題曲 Official Music Video.mp3"},
{name:"梁靜茹 Fish Leong【為我好 For My Own Good】Official Music Video.mp3",artist:"NA",src:"70_80_typical/梁靜茹 Fish Leong【為我好 For My Own Good】Official Music Video.mp3"},
{name:"梁靜茹 Fish Leong【接受 Acceptance】Official Music Video.mp3",artist:"NA",src:"70_80_typical/梁靜茹 Fish Leong【接受 Acceptance】Official Music Video.mp3"},
{name:"梁靜茹 Fish Leong【無條件為你 Unconditionally for you】中視「貞女烈女豪放女」主題曲 Official Music Video.mp3",artist:"NA",src:"70_80_typical/梁靜茹 Fish Leong【無條件為你 Unconditionally for you】中視「貞女烈女豪放女」主題曲 Official Music Video.mp3"},
{name:"梁靜茹 Fish Leong【絲路 Silkroad of Love】Official Music Video.mp3",artist:"NA",src:"70_80_typical/梁靜茹 Fish Leong【絲路 Silkroad of Love】Official Music Video.mp3"},
{name:"梁靜茹 Fish Leong【寧夏 Quiet Summer】Official Music Video.mp3",artist:"NA",src:"70_80_typical/梁靜茹 Fish Leong【寧夏 Quiet Summer】Official Music Video.mp3"},
{name:"梁靜茹 Fish Leong【聽不到 Can't Hear】Official Music Video.mp3",artist:"NA",src:"70_80_typical/梁靜茹 Fish Leong【聽不到 Can't Hear】Official Music Video.mp3"},
{name:"梁靜茹-沒有如果 MV(480P).mp3",artist:"NA",src:"70_80_typical/梁靜茹-沒有如果 MV(480P).mp3"},
{name:"梁靜茹-暖暖.mp3",artist:"NA",src:"70_80_typical/梁靜茹-暖暖.mp3"},
{name:"梁靜茹-會呼吸的痛MV.mp3",artist:"NA",src:"70_80_typical/梁靜茹-會呼吸的痛MV.mp3"},
{name:"莫文蔚 Karen Mok【陰天 Overcast】Official Music Video.mp3",artist:"NA",src:"70_80_typical/莫文蔚 Karen Mok【陰天 Overcast】Official Music Video.mp3"},
{name:"許茹芸 - 如果雲知道  The Cloud Knows (by Valen Hsu).mp3",artist:"NA",src:"70_80_typical/許茹芸 - 如果雲知道  The Cloud Knows (by Valen Hsu).mp3"},
{name:"許茹芸 - 男人女人 MV  [HQ清晰版].mp3",artist:"NA",src:"70_80_typical/許茹芸 - 男人女人 MV  [HQ清晰版].mp3"},
{name:"許茹芸 - 淚海.mp3",artist:"NA",src:"70_80_typical/許茹芸 - 淚海.mp3"},
{name:"許紹洋 Ambrouse Hui【幸福的瞬間】Official Music Video.mp3",artist:"NA",src:"70_80_typical/許紹洋 Ambrouse Hui【幸福的瞬間】Official Music Video.mp3"},
{name:"許紹洋 花香.mp3",artist:"NA",src:"70_80_typical/許紹洋 花香.mp3"},
{name:"許慧欣 - 七月七日晴(歌詞版).mp3",artist:"NA",src:"70_80_typical/許慧欣 - 七月七日晴(歌詞版).mp3"},
{name:"許慧欣 孤單芭蕾.mp3",artist:"NA",src:"70_80_typical/許慧欣 孤單芭蕾.mp3"},
{name:"許慧欣 愛情抗體.mp3",artist:"NA",src:"70_80_typical/許慧欣 愛情抗體.mp3"},
{name:"郭采潔 Amber - 誠實地想你 Missing You Honestly (official官方完整版MV).mp3",artist:"NA",src:"70_80_typical/郭采潔 Amber - 誠實地想你 Missing You Honestly (official官方完整版MV).mp3"},
{name:"郭靜 Claire Kuo - 下一個天亮 (官方版MV).mp3",artist:"NA",src:"70_80_typical/郭靜 Claire Kuo - 下一個天亮 (官方版MV).mp3"},
{name:"郭靜 Claire Kuo - 心牆 (官方版MV).mp3",artist:"NA",src:"70_80_typical/郭靜 Claire Kuo - 心牆 (官方版MV).mp3"},
{name:"郭靜 Claire Kuo - 仨人 (官方版MV).mp3",artist:"NA",src:"70_80_typical/郭靜 Claire Kuo - 仨人 (官方版MV).mp3"},
{name:"郭靜 Claire Kuo - 我不想忘記你 (官方版MV).mp3",artist:"NA",src:"70_80_typical/郭靜 Claire Kuo - 我不想忘記你 (官方版MV).mp3"},
{name:"陳小春 - 神啊救救我.mp3",artist:"NA",src:"70_80_typical/陳小春 - 神啊救救我.mp3"},
{name:"陳小春 Jordan Chan - 古墓愛情 (Official MV).mp3",artist:"NA",src:"70_80_typical/陳小春 Jordan Chan - 古墓愛情 (Official MV).mp3"},
{name:"陳小春 Jordan Chan – 獨家記憶 (Official Music Video).mp3",artist:"NA",src:"70_80_typical/陳小春 Jordan Chan – 獨家記憶 (Official Music Video).mp3"},
{name:"陳奕迅 - 愛情轉移 KTV.mp3",artist:"NA",src:"70_80_typical/陳奕迅 - 愛情轉移 KTV.mp3"},
{name:"陳奕迅 Eason Chan《K歌之王(國)》[Official MV].mp3",artist:"NA",src:"70_80_typical/陳奕迅 Eason Chan《K歌之王(國)》[Official MV].mp3"},
{name:"陳奕迅 Eason Chan《十年(國) [OT  明年今日]》[Official MV].mp3",artist:"NA",src:"70_80_typical/陳奕迅 Eason Chan《十年(國) [OT  明年今日]》[Official MV].mp3"},
{name:"陳奕迅 Eason Chan《你的背包(國)》[Official MV].mp3",artist:"NA",src:"70_80_typical/陳奕迅 Eason Chan《你的背包(國)》[Official MV].mp3"},
{name:"陳嘉唯 Renee Chen - 我等的人會是誰 (official官方完整版MV).mp3",artist:"NA",src:"70_80_typical/陳嘉唯 Renee Chen - 我等的人會是誰 (official官方完整版MV).mp3"},
{name:"陳綺貞 Cheer Chen【旅行的意義 Travel is Meaningful】Official Music Video (官方HD高畫質版).mp3",artist:"NA",src:"70_80_typical/陳綺貞 Cheer Chen【旅行的意義 Travel is Meaningful】Official Music Video (官方HD高畫質版).mp3"},
{name:"陳曉東-心理遊戲MV.mp3",artist:"NA",src:"70_80_typical/陳曉東-心理遊戲MV.mp3"},
{name:"陶? David Tao - 今天妳要嫁給我 Marry Me Today feat. 蔡依林 Jolin Tsai (官方完整版MV).mp3",artist:"NA",src:"70_80_typical/陶? David Tao - 今天妳要嫁給我 Marry Me Today feat. 蔡依林 Jolin Tsai (官方完整版MV).mp3"},
{name:"陶? David Tao – 黑色柳丁 Black Tangerine (官方完整版MV).mp3",artist:"NA",src:"70_80_typical/陶? David Tao – 黑色柳丁 Black Tangerine (官方完整版MV).mp3"},
{name:"陶?-愛很簡單.mp3",artist:"NA",src:"70_80_typical/陶?-愛很簡單.mp3"},
{name:"陶晶瑩(陶子)《太委屈》官方MV (Official Music Video).mp3",artist:"NA",src:"70_80_typical/陶晶瑩(陶子)《太委屈》官方MV (Official Music Video).mp3"},
{name:"棉花糖 Katncandix2 - 欠一個勇敢.mp3",artist:"NA",src:"70_80_typical/棉花糖 Katncandix2 - 欠一個勇敢.mp3"},
{name:"棉花糖 katncandix2 -【再見王子】[Official Music Video].mp3",artist:"NA",src:"70_80_typical/棉花糖 katncandix2 -【再見王子】[Official Music Video].mp3"},
{name:"游鴻明 Chris Yu - 孟婆湯.mp3",artist:"NA",src:"70_80_typical/游鴻明 Chris Yu - 孟婆湯.mp3"},
{name:"游鴻明 Chris Yu - 第一千個晝夜.mp3",artist:"NA",src:"70_80_typical/游鴻明 Chris Yu - 第一千個晝夜.mp3"},
{name:"游鴻明　孟婆湯.mp3",artist:"NA",src:"70_80_typical/游鴻明　孟婆湯.mp3"},
{name:"游鴻明 愛我的人和我愛的人.mp3",artist:"NA",src:"70_80_typical/游鴻明 愛我的人和我愛的人.mp3"},
{name:"痞子英雄 超好聽插曲 - 關於我們 - 痞克四.mp3",artist:"NA",src:"70_80_typical/痞子英雄 超好聽插曲 - 關於我們 - 痞克四.mp3"},
{name:"紫禁之巔 - 背影 (OTFC MV).mp3",artist:"NA",src:"70_80_typical/紫禁之巔 - 背影 (OTFC MV).mp3"},
{name:"順子 Shunza【回家 Go home】Official Music Video.mp3",artist:"NA",src:"70_80_typical/順子 Shunza【回家 Go home】Official Music Video.mp3"},
{name:"黃小琥 沒那麼簡單- 華納official HQ官方版MV.mp3",artist:"NA",src:"70_80_typical/黃小琥 沒那麼簡單- 華納official HQ官方版MV.mp3"},
{name:"黃立行 Stanley Huang - 音浪 Sound Wave (official官方完整版MV).mp3",artist:"NA",src:"70_80_typical/黃立行 Stanley Huang - 音浪 Sound Wave (official官方完整版MV).mp3"},
{name:"黃品源 Huang Pin Yuan【小薇 Xiao Wei】Official Music Video.mp3",artist:"NA",src:"70_80_typical/黃品源 Huang Pin Yuan【小薇 Xiao Wei】Official Music Video.mp3"},
{name:"黃美珍Jane Huang – 途中 (「愛上巧克力」片尾曲  Lyric Video).mp3",artist:"NA",src:"70_80_typical/黃美珍Jane Huang – 途中 (「愛上巧克力」片尾曲  Lyric Video).mp3"},
{name:"黃湘怡 Stella Huang - 吻雨.mp3",artist:"NA",src:"70_80_typical/黃湘怡 Stella Huang - 吻雨.mp3"},
{name:"黃義達 - 那女孩對我說.mp3",artist:"NA",src:"70_80_typical/黃義達 - 那女孩對我說.mp3"},
{name:"黃義達 - 顯微鏡下的愛情.mp3",artist:"NA",src:"70_80_typical/黃義達 - 顯微鏡下的愛情.mp3"},
{name:"黃義達 Yida Huang - 那女孩對我說.mp3",artist:"NA",src:"70_80_typical/黃義達 Yida Huang - 那女孩對我說.mp3"},
{name:"黑澀會美眉 - 123木頭人 (官方版MV).mp3",artist:"NA",src:"70_80_typical/黑澀會美眉 - 123木頭人 (官方版MV).mp3"},
{name:"新文字文件.bat",artist:"NA",src:"70_80_typical/新文字文件.bat"},
{name:"楊乃文『女爵』官方版(Official Music Video).mp3",artist:"NA",src:"70_80_typical/楊乃文『女爵』官方版(Official Music Video).mp3"},
{name:"楊丞琳 Rainie Yang - 任意門.mp3",artist:"NA",src:"70_80_typical/楊丞琳 Rainie Yang - 任意門.mp3"},
{name:"楊丞琳 Rainie Yang - 我們都傻.mp3",artist:"NA",src:"70_80_typical/楊丞琳 Rainie Yang - 我們都傻.mp3"},
{name:"楊丞琳 Rainie Yang - 雨愛.mp3",artist:"NA",src:"70_80_typical/楊丞琳 Rainie Yang - 雨愛.mp3"},
{name:"楊丞琳 Rainie Yang - 缺氧.mp3",artist:"NA",src:"70_80_typical/楊丞琳 Rainie Yang - 缺氧.mp3"},
{name:"楊丞琳 Rainie Yang - 帶我走.mp3",artist:"NA",src:"70_80_typical/楊丞琳 Rainie Yang - 帶我走.mp3"},
{name:"楊丞琳 Rainie Yang - 理想情人.mp3",artist:"NA",src:"70_80_typical/楊丞琳 Rainie Yang - 理想情人.mp3"},
{name:"楊丞琳 Rainie Yang - 曖昧.mp3",artist:"NA",src:"70_80_typical/楊丞琳 Rainie Yang - 曖昧.mp3"},
{name:"楊培安 愛上你是一個錯.mp3",artist:"NA",src:"70_80_typical/楊培安 愛上你是一個錯.mp3"},
{name:"楊培安-痛也?不出口的我.mp3",artist:"NA",src:"70_80_typical/楊培安-痛也?不出口的我.mp3"},
{name:"溫嵐 傻瓜.mp3",artist:"NA",src:"70_80_typical/溫嵐 傻瓜.mp3"},
{name:"溫嵐(Landy Wen)- 北斗星 Official Music Video.mp3",artist:"NA",src:"70_80_typical/溫嵐(Landy Wen)- 北斗星 Official Music Video.mp3"},
{name:"溫嵐《熱浪》Official 完整版 MV [HD].mp3",artist:"NA",src:"70_80_typical/溫嵐《熱浪》Official 完整版 MV [HD].mp3"},
{name:"萬芳 Wan Fang【新不了情 New everlasting love】Official Music Video.mp3",artist:"NA",src:"70_80_typical/萬芳 Wan Fang【新不了情 New everlasting love】Official Music Video.mp3"},
{name:"路嘉欣 (Jozie Lu) - 黑色天空(Black Sky) Official Music Video.mp3",artist:"NA",src:"70_80_typical/路嘉欣 (Jozie Lu) - 黑色天空(Black Sky) Official Music Video.mp3"},
{name:"遇到（歌詞）方雅賢.mp3",artist:"NA",src:"70_80_typical/遇到（歌詞）方雅賢.mp3"},
{name:"蜜雪薇琪 Michelle & Vickie - 一千零一夜.mp3",artist:"NA",src:"70_80_typical/蜜雪薇琪 Michelle & Vickie - 一千零一夜.mp3"},
{name:"蜜雪薇琪 Michelle & Vickie - 愛斯基摩.mp3",artist:"NA",src:"70_80_typical/蜜雪薇琪 Michelle & Vickie - 愛斯基摩.mp3"},
{name:"蜜雪薇琪 Michelle & Vickie - 獨立.mp3",artist:"NA",src:"70_80_typical/蜜雪薇琪 Michelle & Vickie - 獨立.mp3"},
{name:"趙之璧 Bibi Chao【在你和天空之間 Between you and the sky】Official Music Video.mp3",artist:"NA",src:"70_80_typical/趙之璧 Bibi Chao【在你和天空之間 Between you and the sky】Official Music Video.mp3"},
{name:"趙之璧 Bibi Chao【快樂是自找的】Official Music Video.mp3",artist:"NA",src:"70_80_typical/趙之璧 Bibi Chao【快樂是自找的】Official Music Video.mp3"},
{name:"輕鬆玩 忘了.mp3",artist:"NA",src:"70_80_typical/輕鬆玩 忘了.mp3"},
{name:"輕鬆玩樂團　看清.mp3",artist:"NA",src:"70_80_typical/輕鬆玩樂團　看清.mp3"},
{name:"劉力揚 Jeno Liu [禮物 Gift] Official MV.mp3",artist:"NA",src:"70_80_typical/劉力揚 Jeno Liu [禮物 Gift] Official MV.mp3"},
{name:"劉若英 Rene Liu【成全 Step aside】Official Music Video.mp3",artist:"NA",src:"70_80_typical/劉若英 Rene Liu【成全 Step aside】Official Music Video.mp3"},
{name:"劉若英 Rene Liu【很愛很愛你 Love you so much】Official Music Video.mp3",artist:"NA",src:"70_80_typical/劉若英 Rene Liu【很愛很愛你 Love you so much】Official Music Video.mp3"},
{name:"劉若英 Rene Liu【後來 Later】Official Music Video.mp3",artist:"NA",src:"70_80_typical/劉若英 Rene Liu【後來 Later】Official Music Video.mp3"},
{name:"劉若英 Rene Liu【當愛在靠近】Official Music Video.mp3",artist:"NA",src:"70_80_typical/劉若英 Rene Liu【當愛在靠近】Official Music Video.mp3"},
{name:"劉德華 ? 忘情水.mp3",artist:"NA",src:"70_80_typical/劉德華 ? 忘情水.mp3"},
{name:"嘻唰唰 by 花儿??.mp3",artist:"NA",src:"70_80_typical/嘻唰唰 by 花儿??.mp3"},
{name:"潘瑋柏 我的麥克風.mp3",artist:"NA",src:"70_80_typical/潘瑋柏 我的麥克風.mp3"},
{name:"蔡依林 Jolin Tsai -  特務J  (華納official 官方完整版MV).mp3",artist:"NA",src:"70_80_typical/蔡依林 Jolin Tsai -  特務J  (華納official 官方完整版MV).mp3"},
{name:"蔡依林 Jolin Tsai -  舞孃  (華納official 官方完整版MV).mp3",artist:"NA",src:"70_80_typical/蔡依林 Jolin Tsai -  舞孃  (華納official 官方完整版MV).mp3"},
{name:"蔡依林 Jolin Tsai - 天空.mp3",artist:"NA",src:"70_80_typical/蔡依林 Jolin Tsai - 天空.mp3"},
{name:"蔡依林 Jolin Tsai - 布拉格廣場.mp3",artist:"NA",src:"70_80_typical/蔡依林 Jolin Tsai - 布拉格廣場.mp3"},
{name:"蔡依林 Jolin Tsai - 看我七十二變.mp3",artist:"NA",src:"70_80_typical/蔡依林 Jolin Tsai - 看我七十二變.mp3"},
{name:"蔡依林 Jolin Tsai - 倒帶.mp3",artist:"NA",src:"70_80_typical/蔡依林 Jolin Tsai - 倒帶.mp3"},
{name:"蔡依林 Jolin Tsai - 馬德里不思議 A Wonder In Madrid (華納official 官方完整版MV).mp3",artist:"NA",src:"70_80_typical/蔡依林 Jolin Tsai - 馬德里不思議 A Wonder In Madrid (華納official 官方完整版MV).mp3"},
{name:"蔡依林 Jolin Tsai - 野蠻遊戲.mp3",artist:"NA",src:"70_80_typical/蔡依林 Jolin Tsai - 野蠻遊戲.mp3"},
{name:"蔡依林 Jolin Tsai - 愛情三十六計.mp3",artist:"NA",src:"70_80_typical/蔡依林 Jolin Tsai - 愛情三十六計.mp3"},
{name:"蔡依林 Jolin Tsai - 睜一隻眼閉一隻眼.mp3",artist:"NA",src:"70_80_typical/蔡依林 Jolin Tsai - 睜一隻眼閉一隻眼.mp3"},
{name:"蔡依林 Jolin Tsai - 說愛你.mp3",artist:"NA",src:"70_80_typical/蔡依林 Jolin Tsai - 說愛你.mp3"},
{name:"蔡依林 Jolin Tsai - 檸檬草的味道.mp3",artist:"NA",src:"70_80_typical/蔡依林 Jolin Tsai - 檸檬草的味道.mp3"},
{name:"蔡依林 Jolin Tsai - 騎士精神.mp3",artist:"NA",src:"70_80_typical/蔡依林 Jolin Tsai - 騎士精神.mp3"},
{name:"蔡依林 Jolin Tsai【你怎麼連話都說不清楚】HQ.mp3",artist:"NA",src:"70_80_typical/蔡依林 Jolin Tsai【你怎麼連話都說不清楚】HQ.mp3"},
{name:"蔡依林 美人計- 華納official HQ官方版MV.mp3",artist:"NA",src:"70_80_typical/蔡依林 美人計- 華納official HQ官方版MV.mp3"},
{name:"蔡依林 無言以對-華納official HQ官方版MV.mp3",artist:"NA",src:"70_80_typical/蔡依林 無言以對-華納official HQ官方版MV.mp3"},
{name:"蔡依林—我知道你很??.mp3",artist:"NA",src:"70_80_typical/蔡依林—我知道你很??.mp3"},
{name:"蔡旻佑-我可以.mp3",artist:"NA",src:"70_80_typical/蔡旻佑-我可以.mp3"},
{name:"蔡健雅 Tanya Chua - Beautiful Love (official 官方完整版MV).mp3",artist:"NA",src:"70_80_typical/蔡健雅 Tanya Chua - Beautiful Love (official 官方完整版MV).mp3"},
{name:"蔡健雅 Tanya Chua - 雙棲動物 Amphibian (official 官方完整版MV).mp3",artist:"NA",src:"70_80_typical/蔡健雅 Tanya Chua - 雙棲動物 Amphibian (official 官方完整版MV).mp3"},
{name:"蔡健雅 無底洞.mp3",artist:"NA",src:"70_80_typical/蔡健雅 無底洞.mp3"},
{name:"鄧福如 AFU《如果有如果》官方MV (Official Music Video).mp3",artist:"NA",src:"70_80_typical/鄧福如 AFU《如果有如果》官方MV (Official Music Video).mp3"},
{name:"鄭秀文 Sammi Cheng -《獨一無二》Official MV (國).mp3",artist:"NA",src:"70_80_typical/鄭秀文 Sammi Cheng -《獨一無二》Official MV (國).mp3"},
{name:"鄭秀文Sammi Cheng -《眉飛色舞》Official MV （國）（粵：煞科).mp3",artist:"NA",src:"70_80_typical/鄭秀文Sammi Cheng -《眉飛色舞》Official MV （國）（粵：煞科).mp3"},
{name:"銼冰進行曲 - 阿雅.mp3",artist:"NA",src:"70_80_typical/銼冰進行曲 - 阿雅.mp3"},
{name:"燃燒-孫楠.mp3",artist:"NA",src:"70_80_typical/燃燒-孫楠.mp3"},
{name:"燕尾蝶 by 梁靜茹.mp3",artist:"NA",src:"70_80_typical/燕尾蝶 by 梁靜茹.mp3"},
{name:"蕭亞軒 Elva Hsiao -  我喜歡你快樂 I Want You To Be Happy (官方完整版MV).mp3",artist:"NA",src:"70_80_typical/蕭亞軒 Elva Hsiao -  我喜歡你快樂 I Want You To Be Happy (官方完整版MV).mp3"},
{name:"蕭亞軒 Elva Hsiao -  進行式 Fell In Love feat.胡彥斌 ( 官方完整版MV).mp3",artist:"NA",src:"70_80_typical/蕭亞軒 Elva Hsiao -  進行式 Fell In Love feat.胡彥斌 ( 官方完整版MV).mp3"},
{name:"蕭亞軒 Elva Hsiao -  愛的主打歌 Theme Song Of Love  (官方完整版MV).mp3",artist:"NA",src:"70_80_typical/蕭亞軒 Elva Hsiao -  愛的主打歌 Theme Song Of Love  (官方完整版MV).mp3"},
{name:"蕭亞軒 Elva Hsiao - CAPPUCCINO (官方完整版MV).mp3",artist:"NA",src:"70_80_typical/蕭亞軒 Elva Hsiao - CAPPUCCINO (官方完整版MV).mp3"},
{name:"蕭亞軒 Elva Hsiao - 一個人的精彩  My Exciting Solitary Life (官方完整KARAOKE版MV).mp3",artist:"NA",src:"70_80_typical/蕭亞軒 Elva Hsiao - 一個人的精彩  My Exciting Solitary Life (官方完整KARAOKE版MV).mp3"},
{name:"蕭亞軒 Elva Hsiao - 他和她的故事 The Romance About He & She  ( 官方完整版MV).mp3",artist:"NA",src:"70_80_typical/蕭亞軒 Elva Hsiao - 他和她的故事 The Romance About He & She  ( 官方完整版MV).mp3"},
{name:"蕭亞軒 Elva Hsiao - 因為你 Because Of You  ( 官方完整版MV).mp3",artist:"NA",src:"70_80_typical/蕭亞軒 Elva Hsiao - 因為你 Because Of You  ( 官方完整版MV).mp3"},
{name:"蕭亞軒 Elva Hsiao - 最熟悉的陌生人 The Most Familiar Stranger (官方完整版MV).mp3",artist:"NA",src:"70_80_typical/蕭亞軒 Elva Hsiao - 最熟悉的陌生人 The Most Familiar Stranger (官方完整版MV).mp3"},
{name:"蕭亞軒 Elva Hsiao - 薔薇 Blossom In Red (官方完整版MV).mp3",artist:"NA",src:"70_80_typical/蕭亞軒 Elva Hsiao - 薔薇 Blossom In Red (官方完整版MV).mp3"},
{name:"蕭賀碩~我愛你salanheo完整版mv.mp3",artist:"NA",src:"70_80_typical/蕭賀碩~我愛你salanheo完整版mv.mp3"},
{name:"蕭閎仁 Hung-Jen Hsiao - 看袂落去.mp3",artist:"NA",src:"70_80_typical/蕭閎仁 Hung-Jen Hsiao - 看袂落去.mp3"},
{name:"蕭敬騰  背叛~清晰版@超級星光大道.mp3",artist:"NA",src:"70_80_typical/蕭敬騰  背叛~清晰版@超級星光大道.mp3"},
{name:"蕭敬騰 王妃-華納official HQ官方版MV.mp3",artist:"NA",src:"70_80_typical/蕭敬騰 王妃-華納official HQ官方版MV.mp3"},
{name:"蕭敬騰 阿飛的小蝴蝶-華納 official HQ官方版MV.mp3",artist:"NA",src:"70_80_typical/蕭敬騰 阿飛的小蝴蝶-華納 official HQ官方版MV.mp3"},
{name:"蕭煌奇 你是我的眼 (2008 KTV).mp3",artist:"NA",src:"70_80_typical/蕭煌奇 你是我的眼 (2008 KTV).mp3"},
{name:"蕭蕭 - 握不住的他.mp3",artist:"NA",src:"70_80_typical/蕭蕭 - 握不住的他.mp3"},
{name:"戴佩妮  Penny Tai - 怎樣 What If We Still Stay Together (官方完整版MV).mp3",artist:"NA",src:"70_80_typical/戴佩妮  Penny Tai - 怎樣 What If We Still Stay Together (官方完整版MV).mp3"},
{name:"戴佩妮 Penny Tai - 你要的愛 The Love You Want (官方完整KARAOKE版MV).mp3",artist:"NA",src:"70_80_typical/戴佩妮 Penny Tai - 你要的愛 The Love You Want (官方完整KARAOKE版MV).mp3"},
{name:"戴佩妮 Penny Tai - 防...空洞 Safe Place For Love (官方完整版MV).mp3",artist:"NA",src:"70_80_typical/戴佩妮 Penny Tai - 防...空洞 Safe Place For Love (官方完整版MV).mp3"},
{name:"戴佩妮 Penny Tai - 街角的祝福 Blessing From The Street Corner (官方完整版MV).mp3",artist:"NA",src:"70_80_typical/戴佩妮 Penny Tai - 街角的祝福 Blessing From The Street Corner (官方完整版MV).mp3"},
{name:"戴愛玲 Ailing Dai - 對的人 MR. Right (官方完整版MV).mp3",artist:"NA",src:"70_80_typical/戴愛玲 Ailing Dai - 對的人 MR. Right (官方完整版MV).mp3"},
{name:"藍又時 - 孤單心事.mp3",artist:"NA",src:"70_80_typical/藍又時 - 孤單心事.mp3"},
{name:"羅大佑 童年.mp3",artist:"NA",src:"70_80_typical/羅大佑 童年.mp3"},
{name:"羅志祥 - 愛轉角 （高清完整版) MV.mp3",artist:"NA",src:"70_80_typical/羅志祥 - 愛轉角 （高清完整版) MV.mp3"},
{name:"羅志祥 - 愛轉角 MV.mp3",artist:"NA",src:"70_80_typical/羅志祥 - 愛轉角 MV.mp3"},
{name:"羅美玲 愛一直閃亮.mp3",artist:"NA",src:"70_80_typical/羅美玲 愛一直閃亮.mp3"},
{name:"蘇打綠 sodagreen -【小情歌】Official Music Video.mp3",artist:"NA",src:"70_80_typical/蘇打綠 sodagreen -【小情歌】Official Music Video.mp3"},
{name:"蘇打綠 sodagreen -【無與倫比的美麗】Official Music Video.mp3",artist:"NA",src:"70_80_typical/蘇打綠 sodagreen -【無與倫比的美麗】Official Music Video.mp3"},
{name:"蘇永康-相遇太早.mp3",artist:"NA",src:"70_80_typical/蘇永康-相遇太早.mp3"},
{name:"蘇慧倫 Tarcy Su【Lemon Tree】Official Music Video.mp3",artist:"NA",src:"70_80_typical/蘇慧倫 Tarcy Su【Lemon Tree】Official Music Video.mp3"},
{name:"蘇慧倫 Tarcy Su【鴨子 The Duck】Official Music Video.mp3",artist:"NA",src:"70_80_typical/蘇慧倫 Tarcy Su【鴨子 The Duck】Official Music Video.mp3"},
{name:"聽不到 梁靜茹.wmv.mp3",artist:"NA",src:"70_80_typical/聽不到 梁靜茹.wmv.mp3"}

]
